import typing

from BaseClasses import Location


class LocationData:
    name: str = ""
    id: int = 0x00

    def __init__(self, name, id_):
        self.name = name
        self.id = id_


class TTYDLocation(Location):
    game: str = "Mario & Luigi Superstar Saga"


rogueport: typing.List[LocationData] = [
    LocationData("Rogueport Docks: HP Drain", 78780000),
    LocationData("Rogueport Docks: Star Piece", 78780001),
    LocationData("Rogueport Center: Goombella", 78780002),
    LocationData("Rogueport Center: Contact Lens", 78780003),
    LocationData("Rogueport Center: Old Letter", 78780004),
    LocationData("Rogueport Center: Attack FX G", 78780005),
    LocationData("Rogueport Center: Attack FX P", 78780006),
    LocationData("Rogueport Center: Boo's Sheet", 78780007),
    LocationData("Rogueport Center: Close Call", 78780008),
    LocationData("Rogueport Center: Close Call P", 78780009),
    LocationData("Rogueport Center: Damage Dodge", 78780010),
    LocationData("Rogueport Center: Damage Dodge P", 78780011),
    LocationData("Rogueport Center: Double Pain", 78780012),
    LocationData("Rogueport Center: Dried Shroom", 78780013),
    LocationData("Rogueport Center: Earthquake", 78780014),
    LocationData("Rogueport Center: Fire Drive", 78780015),
    LocationData("Rogueport Center: Fire Flower", 78780016),
    LocationData("Rogueport Center: First Attack", 78780017),
    LocationData("Rogueport Center: FP Drain", 78780018),
    LocationData("Rogueport Center: Fright Mask", 78780019),
    LocationData("Rogueport Center: Hammerman", 78780020),
    LocationData("Rogueport Center: Happy Flower", 78780021),
    LocationData("Rogueport Center: Head Rattle", 78780022),
    LocationData("Rogueport Center: Honey Syrup", 78780023),
    LocationData("Rogueport Center: Ice Smash", 78780024),
    LocationData("Rogueport Center: Jammin' Jelly", 78780025),
    LocationData("Rogueport Center: Jumpman", 78780026),
    LocationData("Rogueport Center: Last Stand", 78780027),
    LocationData("Rogueport Center: Last Stand P", 78780028),
    LocationData("Rogueport Center: Mega Rush", 78780029),
    LocationData("Rogueport Center: Mushroom", 78780030),
    LocationData("Rogueport Center: Piercing Blow", 78780031),
    LocationData("Rogueport Center: Power Jump", 78780032),
    LocationData("Rogueport Center: Power Rush", 78780033),
    LocationData("Rogueport Center: Power Rush P", 78780034),
    LocationData("Rogueport Center: Pretty Lucky P", 78780035),
    LocationData("Rogueport Center: Repel Cape", 78780036),
    LocationData("Rogueport Center: Shooting Star", 78780037),
    LocationData("Rogueport Center: Shrink Stomp", 78780038),
    LocationData("Rogueport Center: Simplifier", 78780039),
    LocationData("Rogueport Center: Simplifier (6 Chapters Cleared)", 78780040),
    LocationData("Rogueport Center: Sleepy Sheep", 78780041),
    LocationData("Rogueport Center: Sleepy Stomp", 78780042),
    LocationData("Rogueport Center: Slow Go", 78780043),
    LocationData("Rogueport Center: Soft Stomp", 78780044),
    LocationData("Rogueport Center: Star Piece 1", 78780045),
    LocationData("Rogueport Center: Star Piece 2", 78780046),
    LocationData("Rogueport Center: Star Piece 3", 78780047),
    LocationData("Rogueport Center: Star Piece 4", 78780048),
    LocationData("Rogueport Center: Star Piece 5", 78780049),
    LocationData("Rogueport Center: Stopwatch", 78780050),
    LocationData("Rogueport Center: Super Appeal", 78780051),
    LocationData("Rogueport Center: Super Appeal P", 78780052),
    LocationData("Rogueport Center: Tasty Tonic", 78780053),
    LocationData("Rogueport Center: Timing Tutor", 78780054),
    LocationData("Rogueport Center: Ultra Hammer", 78780055),
    LocationData("Rogueport Center: Ultra Shroom", 78780056),
    LocationData("Rogueport Center: Unsimplifier", 78780057),
    LocationData("Rogueport Center: Unsimplifier (6 Chapters Cleared)", 78780058),
    LocationData("Rogueport Center: W Emblem", 78780059),
    LocationData("Rogueport Eastside: Power Smash", 78780060),
    LocationData("Rogueport Eastside: Double Dip", 78780061),
    LocationData("Rogueport Eastside: Shine Sprite 1", 78780062),
    LocationData("Rogueport Eastside: Shine Sprite 2", 78780063),
    LocationData("Rogueport Eastside: Star Piece 1", 78780064),
    LocationData("Rogueport Eastside: Star Piece 2", 78780065),
    LocationData("Rogueport Eastside: Star Piece 3", 78780066),
    LocationData("Rogueport Eastside: Star Piece 4", 78780067),
    LocationData("Rogueport Eastside: Star Piece 5", 78780068),
]

rogueport_westside: typing.List[LocationData] = [
    LocationData("Rogueport Westside: Blimp Ticket", 0x49d95f),
    LocationData("Rogueport Westside: Train Ticket", 0x49db02),
    LocationData("Rogueport Westside: Cake Mix", 0x49daea),
    LocationData("Rogueport Westside: Dizzy Dial", 0x49dab5),
    LocationData("Rogueport Westside: Dried Shroom", 0x49db0f),
    LocationData("Rogueport Westside: FP Plus", 0x49db22),
    LocationData("Rogueport Westside: Gold Bar x3", 0x49db2a),
    LocationData("Rogueport Westside: Hammer Throw", 0x49db32),
    LocationData("Rogueport Westside: HP Plus", 0x49db87),
    LocationData("Rogueport Westside: HP Plus P", 0x49db97),
    LocationData("Rogueport Westside: Jammin' Jelly", 0x49dbac),
    LocationData("Rogueport Westside: Life Shroom", 0x49dbb4),
    LocationData("Rogueport Westside: Lottery Pick", 0x49dbbc),
    LocationData("Rogueport Westside: Mushroom", 0x49dbc9),
    LocationData("Rogueport Westside: Power Jump", 0x49dbd9),
    LocationData("Rogueport Westside: Power Rush", 0x49dbe1),
    LocationData("Rogueport Westside: Power Rush P", 0x49dbee),
    LocationData("Rogueport Westside: Power Smash", 0x49dbfb),
    LocationData("Rogueport Westside: Quake Hammer", 0x49dc08),
    LocationData("Rogueport Westside: Refund", 0x49dc20),
    LocationData("Rogueport Westside: Shine Sprite 1", 0x49dc28),
    LocationData("Rogueport Westside: Shine Sprite 2", 0x49dc4d),
    LocationData("Rogueport Westside: Star Piece 1", 0x49dc7a),
    LocationData("Rogueport Westside: Star Piece 2", 0x49dc82),
    LocationData("Rogueport Westside: Star Piece 3", 0x49dc8f),
    LocationData("Rogueport Westside: Star Piece 4", 0x49dc97),
    LocationData("Rogueport Westside: Super Appeal", 0x49dc9f),
    LocationData("Rogueport Westside: Super Shroom 1", 0x49dcac),
    LocationData("Rogueport Westside: Super Shroom 2", 0x49dcbc),
    LocationData("Rogueport Westside: Thunder Bolt", 0x49dcc4),
    LocationData("Rogueport Westside: Tornado Jump", 0x49dcd1),
    LocationData("Rogueport Westside: Ultra Shroom 1", 0x49dce1),
    LocationData("Rogueport Westside: Ultra Shroom 2", 0x49dcd9),
    LocationData("Rogueport Westside: Volt Shroom", 0x49dcee),
    LocationData("Rogueport Blimp Room: Star Piece 1", 0x49e17f),
    LocationData("Rogueport Blimp Room: Star Piece 2", 0x49e187)
]

sewers: typing.List[LocationData] = [
    LocationData("Rougueport Sewers Town: Attack FX Y", 0x49da42),
    LocationData("Rougueport Sewers Town: Chill Out", 0x49da4a),
    LocationData("Rougueport Sewers Town: Flower Finder", 0x49da52),
    LocationData("Rougueport Sewers Town: Flower Saver", 0x49d9e9),
    LocationData("Rougueport Sewers Town: Flower Saver P", 0x277a45),
    LocationData("Rougueport Sewers Town: Gold Bar", 0x49e5b5),
    LocationData("Rougueport Sewers Town: Gold Bar x3", 0x49e5c8),
    LocationData("Rougueport Sewers Town: Gradual Syrup", 0x49e5d0),
    LocationData("Rougueport Sewers Town: Happy Flower", 0x49da0b),
    LocationData("Rougueport Sewers Town: Happy Heart", 0x49da20),
    LocationData("Rougueport Sewers Town: Happy Heart P", 0x49da18),
    LocationData("Rougueport Sewers Town: Heart Finder", 0x49da42),
    LocationData("Rougueport Sewers Town: Item Hog", 0x49da4a),
    LocationData("Rougueport Sewers Town: Jammin' Jelly", 0x49da52),
    LocationData("Rougueport Sewers Town: Peekaboo", 0x49d9e9),
    LocationData("Rougueport Sewers Town: Power Plus", 0x277a45),
    LocationData("Rougueport Sewers Town: Power Plus P", 0x49e5b5),
    LocationData("Rougueport Sewers Town: Pretty Lucky", 0x49e5c8),
    LocationData("Rougueport Sewers Town: Quick Change", 0x49e5d0),
    LocationData("Rougueport Sewers Town: Shine Sprite", 0x49da0b),
    LocationData("Rougueport Sewers Town: Slow Shroom", 0x49da20),
    LocationData("Rougueport Sewers Town: Soft Stomp", 0x49da42),
    LocationData("Rougueport Sewers Town: Star Piece 1", 0x49da4a),
    LocationData("Rougueport Sewers Town: Star Piece 2", 0x49da52),
    LocationData("Rougueport Sewers Town: Star Piece 3", 0x49d9e9),
    LocationData("Rougueport Sewers Town: Star Piece 4", 0x277a45),
    LocationData("Rougueport Sewers East Entrance: Ultra Mushroom", 0x49e5b5),
    LocationData("Rougueport Sewers East Entrance: Star Piece", 0x49e5c8),
    LocationData("Rougueport Sewers Petal Meadows Pipe: Shine Sprite", 0x49e5d0),
    LocationData("Rogueport Sewers Boggly Woods Pipe: Damage Dodge", 0x49da0b),
    LocationData("Rogueport Sewers Boggly Woods Pipe: Star Piece", 0x49da20),
    LocationData("Rogueport Sewers Black Key Room: Black Key", 0x49da42),
    LocationData("Rogueport Sewers Black Key Room: Happy Heart P", 0x49da4a),
    LocationData("Rogueport Sewers Black Key Room: Pretty Lucky", 0x49da52),
    LocationData("Rogueport Sewers Black Key Room: Star Piece", 0x49d9e9),
    LocationData("Rogueport Sewers Thousand Year Door: Shine Sprite", 0x277a45),
    LocationData("Rogueport Sewers Thousand Year Door: Star Piece", 0x49e5b5),
    LocationData("Rougueport Sewers Pit Entrance: Star Piece", 0x49e5c8),
    LocationData("Rogueport Sewers West Entrance: Flower Saver P", 0x49e5d0),
    LocationData("Rogueport Sewers West Entrance: Shine Sprite", 0x49da0b),
    LocationData("Rogueport Sewers West Entrance: Star Piece 1", 0x49da20),
    LocationData("Rogueport Sewers West Entrance: Star Piece 2", 0x49da42),
    LocationData("Rogueport Sewers East Enemy Hall: Fire Flower", 0x49da4a),
    LocationData("Rogueport Sewers East Enemy Hall: Mushroom", 0x49da52),
    LocationData("Rogueport Sewers East Pipe Room: Shine Sprite", 0x49d9e9),
    LocationData("Rogueport Sewers West Pipe Room: FP Plus", 0x277a45),
    LocationData("Rogueport Sewers West Enemy Hall: Gradual Syrup", 0x49e5b5),
    LocationData("Rogueport Sewers West Enemy Hall: Slow Shroom", 0x49e5c8),
    LocationData("Rogueport Sewers Black Chest Room: Plane Curse", 0x49e5d0),
    LocationData("Rogueport Sewers Black Chest Room: Star Piece", 0x49da0b),
    LocationData("Rogueport Sewers Spania Room: Defend Plus", 0x49da20),
    LocationData("Rogueport Sewers Spania Room: Shine Sprite 1", 0x49da42),
    LocationData("Rogueport Sewers Spania Room: Shine Sprite 2", 0x49da4a),
    LocationData("Rogueport Sewers Spania Room: Shine Sprite 3", 0x49da52),
    LocationData("Rogueport Sewers Spike Room: Spike Shield", 0x49d9e9)
]

petal_right: typing.List[LocationData] = [
    LocationData("Petal Meadows Bridge Room: Coin 2", 0x49e22a),
    LocationData("Petal Meadows Bridge Room: Fire Flower", 0x49e232),
    LocationData("Petal Meadows Bridge Room: Mystery", 0x49e23f),
    LocationData("Petal Meadows First Fort Exterior: Coin 1", 0x49e254),
    LocationData("Petal Meadows First Fort Exterior: Coin 2", 0x49e261),
    LocationData("Petal Meadows First Fort Exterior: POW Block", 0x49e269),
    LocationData("Petal Meadows Second Fort Exterior: Coin", 0x49e271),
    LocationData("Petal Meadows Second Fort Exterior: Fire Flower", 0x49e279),
    LocationData("Petal Meadows Second Fort Exterior: Inn Coupon", 0x49e8fd),
    LocationData("Petal Meadows Sewers West Key Room: Moon Stone", 0x49e90a),
    LocationData("Petal Meadows Sewers: Multibounce", 0x49e91a),
    LocationData("Petal Meadows Sewers East Key Room: Sun Stone", 0x1e9411),
    LocationData("Petalburg Westside: Courage Shell", 0x22913a),
    LocationData("Petalburg Westside: Fire Flower", 0x22890e),
    LocationData("Petalburg Westside: Honey Syrup", 0x228775),
    LocationData("Petalburg Westside: Mr. Softener", 0x1e9431),
    LocationData("Petalburg Westside: Mushroom", 0x277ab2),
    LocationData("Petalburg Westside: POW Block", 0x2779C8),
    LocationData("Petalburg Westside: Star Piece", 0x1E9430),
    LocationData("Petalburg Eastside: Mega Rush P", 0x1E9404),
    LocationData("Petalburg Eastside: Star Piece", 0x1e9405),
    LocationData("Petalburg Eastside: Turtley Leaf", 0x1e9435)
]

petal_left: typing.List[LocationData] = [
    LocationData("Petal Meadows Entrance: Mushroom 1", 0x49e1d6),
    LocationData("Petal Meadows Entrance: Mushroom 2", 0x49e1e3),
    LocationData("Petal Meadows Entrance: Star Piece", 0x49e208),
    LocationData("Petal Meadows Bridge Room: Koops", 0x49e210),
    LocationData("Petal Meadows Bridge Room: Coin 1", 0x49e21d),
    LocationData("Petal Meadows Bridge Room: Star Piece", 0x49e24c),
    LocationData("Petal Meadows Field: 10 Coins", 0x1e9412),
    LocationData("Petal Meadows Field: Close Call", 0x229345),
    LocationData("Petal Meadows Field: Happy Heart", 0x22954d),
    LocationData("Petal Meadows Field: Horsetail", 0x228a17)
]

hooktails_castle: typing.List[LocationData] = [
    LocationData("Hooktail's Castle Drawbridge: HP Plus", 0x49d680),
    LocationData("Hooktail's Castle Entrance: Power Bounce", 0x49d688),
    LocationData("Hooktail's Castle Red Bones Room: Castle Key", 0x49d690),
    LocationData("Hooktail's Castle Red Bones Room: Star Piece", 0x49d69d),
    LocationData("Hooktail's Castle Stair Switch Room: Castle Key", 0x49d6a5),
    LocationData("Hooktail's Castle Stair Switch Room: Shine Sprite", 0x49d6d7),
    LocationData("Hooktail's Castle Stair Switch Room: Star Piece 1", 0x49d6df),
    LocationData("Hooktail's Castle Stair Switch Room: Star Piece 2", 0x49d70b),
    LocationData("Hooktail's Castle Stair Central Staircase: Castle Key", 0x49d71b),
    LocationData("Hooktail's Castle Stair Central Staircase: Last Stand P", 0x49d803),
    LocationData("Hooktail's Castle Stair Central Staircase: Shine Sprite", 0x49d8da),
    LocationData("Hooktail's Castle Stair Central Staircase: Star Piece", 0x49d977),
    LocationData("Hooktail's Castle Prison Entrance: Paper Curse", 0x49d987),
    LocationData("Hooktail's Castle Prison Entrance: Attack FX R", 0x49daa0),
    LocationData("Hooktail's Castle Spikes Room: Black Key 2", 0x49dac5),
    LocationData("Hooktail's Castle Life Shroom Room: Life Shroom", 0x49dad5),
    LocationData("Hooktail's Castle Plane Rafters Room: Star Piece", 0x49dae2),
    LocationData("Hooktail's Castle Hooktail's Room: Diamond Star", 0x49daf2),
    LocationData("Hooktail's Castle Storeroom: Castle Key", 0x49dafa),
    LocationData("Hooktail's Castle Storeroom: Honey Syrup", 0x49db8f),
    LocationData("Hooktail's Castle Storeroom: Mushroom", 0x49dc18),
    LocationData("Hooktail's Castle Storeroom: Shine Sprite", 0x49dc3d),
    LocationData("Hooktail's Castle Up Arrow Room: Up Arrow", 0x49dd30)
]

boggly_woods: typing.List[LocationData] = [
    LocationData("Boggly Woods Shadow Sirens Room: Necklace", 0x49e951),
    LocationData("Boggly Woods Shadow Sirens Room: Honey Syrup", 0x49e959),
    LocationData("Boggly Woods Shadow Sirens Room: Sleepy Sheep", 0x1e9441),
    LocationData("Boggly Woods Tree View: Coin", 0x1e9434),
    LocationData("Boggly Woods Tree View: Inn Coupon", 0x1e9444),
    LocationData("Boggly Woods Plane Panel Room: P-Down D-Up P", 0x49dc65),
    LocationData("Boggly Woods Plane Panel Room: Quake Hammer", 0x49dc5d),
    LocationData("Boggly Woods Plane Panel Room: Shine Sprite", 0x49dc45),
    LocationData("Boggly Woods Plane Panel Room: Star Piece", 0x49dc35),
    LocationData("Boggly Woods Outside Flurrie's House: Star Piece 1", 0x1e9434),
    LocationData("Boggly Woods Outside Flurrie's House: Star Piece 2", 0x1e9444),
    LocationData("Boggly Woods Outside Flurrie's House: Volt Shroom", 0x49dc65),
    LocationData("Boggly Woods Flurrie's House: Flurrie", 0x49dc5d),
    LocationData("Boggly Woods Flurrie's House Backroom: Star Piece", 0x49dc45),
    LocationData("Boggly Woods Flurrie's House Backroom: Super Appeal P", 0x49dc35),
    LocationData("Boggly Woods Outside Great Tree: FP Plus", 0x49dc35)
]

great_tree: typing.List[LocationData] = [
    LocationData("Great Tree Entrance: Coin", 0x49dd20),
    LocationData("Great Tree Entrance: Emerald Star", 0x49dd38),
    LocationData("Great Tree Entrance: Mystic Egg", 0x49dd48),
    LocationData("Great Tree Entrance: Puni Orb", 0x49dd50),
    LocationData("Great Tree 10-Puni Pedestal: Star Piece", 0x49dd5d),
    LocationData("Great Tree Red/Blue Cages: Star Piece", 0x49dd6d),
    LocationData("Great Tree Red Key Room: Coin", 0x49dd82),
    LocationData("Great Tree Red Key Room: Mushroom", 0x49dd8a),
    LocationData("Great Tree Red Key Room: Red Key", 0x49dd9f),
    LocationData("Great Tree Red Key Room: Ultra Shroom", 0x49ddac),
    LocationData("Great Tree Bubble Room: Shine Sprite", 0x49ddc1),
    LocationData("Great Tree Bubble Room: Thunder Rage", 0x49ddc9),
    LocationData("Great Tree Zigzag Room: Coin", 0x49ddd6),
    LocationData("Great Tree Zigzag Room: Damage Dodge P", 0x49ddde),
    LocationData("Great Tree Zigzag Room: Star Piece", 0x49ddee),
    LocationData("Great Tree Shop: Honey Syrup", 0x49ddf6),
    LocationData("Great Tree Shop: HP Drain", 0x49de06),
    LocationData("Great Tree Shop: Ice Storm", 0x49de0e),
    LocationData("Great Tree Shop: Mini Mr.Mini", 0x49de16),
    LocationData("Great Tree Shop: Mushroom", 0x49de29),
    LocationData("Great Tree Shop: Mystery", 0x49de39),
    LocationData("Great Tree Red Key Room: Blue Key", 0x49de41),
    LocationData("Great Tree Red Key Room: Charge", 0x49de49),
    LocationData("Great Tree Red Key Room: Shine Sprite", 0x49de56),
    LocationData("Great Tree Super Boots Room: Super Boots", 0x49de66),
    LocationData("Great Tree 100-Puni Pedestal: Coin", 0x49de73),
    LocationData("Great Tree 100-Puni Pedestal: Star Piece", 0x49de7b),
    LocationData("Great Tree Elevator Pedestal: Mushroom", 0x49de83),
    LocationData("Great Tree Escape Ambush Room: Star Piece", 0x49de8b),
    LocationData("Great Tree Pool Room: Dizzy Dial", 0x49de98),
    LocationData("Great Tree Pool Room: Shine Sprite", 0x49dea0),
    LocationData("Great Tree Pool Room: Shrink Stomp", 0x49dea8),
    LocationData("Great Tree Fake Pedestal: Star Piece", 0x49deb5),
    LocationData("Great Tree Lower Duplex: Coin", 0x49dec2),
    LocationData("Great Tree Middel Duplex: Shine Sprite", 0x49decf),
    LocationData("Great Tree Upper Duplex: Power Punch", 0x49ded7)
]

glitzville: typing.List[LocationData] = [
    LocationData("Glitzville Main Square: Coin", 0x49d7a4),
    LocationData("Glitzville Main Square: Earth Quake", 0x49d7a4),
    LocationData("Glitzville Main Square: Hot Dog", 0x49d7a4),
    LocationData("Glitzville Main Square: Inn Coupon", 0x49d7a4),
    LocationData("Glitzville Main Square: Point Swap", 0x49d7a4),
    LocationData("Glitzville Main Square: Power Plus P", 0x49d7a4),
    LocationData("Glitzville Main Square: Power Punch", 0x49d7a4),
    LocationData("Glitzville Main Square: Repel Cape", 0x49d7a4),
    LocationData("Glitzville Main Square: Shine Sprite", 0x49d7a4),
    LocationData("Glitzville Main Square: Star Piece 1", 0x49d7a4),
    LocationData("Glitzville Main Square: Star Piece 2", 0x49d7a4),
    LocationData("Glitzville Main Square: Star Piece 3", 0x49d7a4),
    LocationData("Glitzville Main Square: Star Piece 4", 0x49d7a4),
    LocationData("Glitzville Main Square: Star Piece 5", 0x49d7a4),
    LocationData("Glitzville Main Square: Storage Key 1", 0x49d7a4),
    LocationData("Glitzville Main Square: Super Hammer", 0x49d7a4),
    LocationData("Glitzville Main Square: Super Shroom", 0x49d7a4),
    LocationData("Glitzville Main Square: Thunder Bolt", 0x49d7a4),
    LocationData("Glitzville Lobby: Star Piece", 0x49d7ac),
    LocationData("Glitzville Lobby: Storage Key 2", 0x49d7b4),
    LocationData("Glitzville Arena: Gold Star", 0x49d7bc),
    LocationData("Glitzville Hall: Last Stand", 0x49d7d8),
    LocationData("Glitzville Promoter's Office: Star Piece 1", 0x49d7e0),
    LocationData("Glitzville Promoter's Office: Star Piece 2", 0x49d7e8),
    LocationData("Glitzville Storage Room: Charge P", 0x49d7f0),
    LocationData("Glitzville Storage Room: HP Plus P", 0x49d7f0),
    LocationData("Glitzville Storage Room: Shine Sprite", 0x49d7f0),
    LocationData("Glitzville Storage Room: Star Piece", 0x49d7f0),
    LocationData("Glitzville Major-League Room: Champ's Belt", 0x1e9433),
    LocationData("Glitzville Major-League Room: Ice Storm", 0x1e9433),
    LocationData("Glitzville Minor-League Room: Dubious Paper", 0x1e9432),
    LocationData("Glitzville Minor-League Room: Yoshi", 0x1e9432),
    LocationData("Glitzville Storage Back Room: Star Piece", 0x251347)
]

twilight_town: typing.List[LocationData] = [
    LocationData("Twilight Town Leftside: Coin", 0x49e16f),
    LocationData("Twilight Town Leftside: Peachy Peach", 0x49e16f),
    LocationData("Twilight Town Leftside: Star Piece 1", 0x49e16f),
    LocationData("Twilight Town Leftside: Star Piece 2", 0x49e16f),
    LocationData("Twilight Town Leftside: Superbombomb", 0x49e16f),
    LocationData("Twilight Town Leftside: Vivian", 0x49e16f),
    LocationData("Twilight Town Rightside: Boo's Sheet", 0x49e194),
    LocationData("Twilight Town Rightside: Defend Plus", 0x49e194),
    LocationData("Twilight Town Rightside: Inn Coupon", 0x49e194),
    LocationData("Twilight Town Rightside: Jammin' Jelly", 0x49e194),
    LocationData("Twilight Town Rightside: Life Shroom 1", 0x49e194),
    LocationData("Twilight Town Rightside: Life Shroom 2", 0x49e194),
    LocationData("Twilight Town Rightside: Maple Syrup", 0x49e194),
    LocationData("Twilight Town Rightside: Spite Pouch", 0x49e194),
    LocationData("Twilight Town Rightside: Star Piece", 0x49e194),
    LocationData("Twilight Town Rightside: Stopwatch", 0x49e194),
    LocationData("Twilight Town Rightside: Super Shroom", 0x49e194),
    LocationData("Twilight Town Rightside: Thunder Rage", 0x49e194),
    LocationData("Twilight Town Rightside: Tube Curse", 0x49e194)
]

twilight_trail: typing.List[LocationData] = [
    LocationData("Twilight Trail Entrance: 10 Coins", 0x49e0a5),
    LocationData("Twilight Trail Entrance: Black Key 3", 0x49e0ad),
    LocationData("Twilight Trail Hyper Goomba Room: 10 Coins", 0x49e0b5),
    LocationData("Twilight Trail Hyper Goomba Room: Coin", 0x49e0b5),
    LocationData("Twilight Trail Hyper Goomba Room: Super Shroom", 0x49e0b5),
    LocationData("Twilight Trail Fallen Tree: Shop Key", 0x49e0bd),
    LocationData("Twilight Trail Fallen Tree: Star Piece 1", 0x49e0bd),
    LocationData("Twilight Trail Fallen Tree: Star Piece 2", 0x49e0bd),
    LocationData("Twilight Trail Dark Woods First Room: 10 Coins", 0x49e0c5),
    LocationData("Twilight Trail Dark Woods First Room: Earthquake", 0x49e0c5),
    LocationData("Twilight Trail Dark Woods Second Room: Hammer Throw", 0x49e0cd),
    LocationData("Twilight Trail Dark Woods Third Room: 10 Coins", 0x49e057),
    LocationData("Twilight Trail Dark Woods Third Room: Shine Sprite", 0x49e057),
    LocationData("Twilight Trail Steeple Exterior: Coin", 0x49e0da),
    LocationData("Twilight Trail Steeple Exterior: Star Piece", 0x49e0da)
]

creepy_steeple: typing.List[LocationData] = [
    LocationData("Creepy Steeple Main Hall: Lucky Start", 0x49e2dc),
    LocationData("Creepy Steeple Main Hall: Steeple Key 1", 0x49e2dc),
    LocationData("Creepy Steeple North Hall: Golden Leaf", 0x49e2e9),
    LocationData("Creepy Steeple Upper Room: Ruby Star", 0x49e2f6),
    LocationData("Creepy Steeple Cookbook Room: Cookbook", 0x49e2fe),
    LocationData("Creepy Steeple Cookbook Room: Ice Smash", 0x49e2fe),
    LocationData("Creepy Steeple Cookbook Room: Shine Sprite", 0x49e2fe),
    LocationData("Creepy Steeple Cookbook Room: Star Piece", 0x49e2fe),
    LocationData("Creepy Steeple Under Statue: Flower Saver", 0x49e306),
    LocationData("Creepy Steeple Boo Chest Room: Star Piece", 0x49e30e),
    LocationData("Creepy Steeple Boo Chest Room: Ultra Mushroom", 0x49e30e),
    LocationData("Creepy Steeple Parrot Room: Mr. Softener", 0x49e316),
    LocationData("Creepy Steeple Parrot Room: Power Plus", 0x49e316),
    LocationData("Creepy Steeple Parrot Room: Star Piece", 0x49e316),
    LocationData("Creepy Steeple Parrot Room: Steeple Key 2", 0x49e316),
    LocationData("Creepy Steeple Parrot Room: The Letter \"P\"", 0x49e316),
    LocationData("Creepy Steeple Well Entrance: Shine Sprite", 0x49e323),
    LocationData("Creepy Steeple Buzzy Room: Tornado Jump", 0x49e32b),
    LocationData("Creepy Steeple Underground Tube Passage: Shine Sprite", 0x49e333)
]

keelhaul_key: typing.List[LocationData] = [
    LocationData("Keelhaul Key Landing Site: Star Piece", 0x49e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 1", 0x49e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 2", 0x49e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 3", 0x49e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 4", 0x49e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 5", 0x49e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 6", 0x49e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 7", 0x49e37d),
    LocationData("Keelhaul Key Town: Chuckola Cola", 0x49e37d),
    LocationData("Keelhaul Key Town: Fire Flower", 0x49e37d),
    LocationData("Keelhaul Key Town: Fright Mask", 0x49e37d),
    LocationData("Keelhaul Key Town: Honey Syrup", 0x49e37d),
    LocationData("Keelhaul Key Town: Ice Storm", 0x49e37d),
    LocationData("Keelhaul Key Town: Sleepy Sheep", 0x49e37d),
    LocationData("Keelhaul Key Town: Star Piece 1", 0x49e37d),
    LocationData("Keelhaul Key Town: Star Piece 2", 0x49e37d),
    LocationData("Keelhaul Key Town: Super Shroom", 0x49e37d),
    LocationData("Keelhaul Key Jungle Entrance: Coin", 0x49e37d),
    LocationData("Keelhaul Key Jungle Entrance: Courage Shell", 0x49e37d),
    LocationData("Keelhaul Key Jungle Entrance: Head Rattle", 0x49e37d),
    LocationData("Keelhaul Key Jungle Entrance: Keel Mango", 0x49e37d),
    LocationData("Keelhaul Key Jungle Entrance: Star Piece", 0x49e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: 10 Coins", 0x49e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Coin 1", 0x49e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Coin 2", 0x49e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Jammin' Jelly", 0x49e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Mini Mr.Mini", 0x49e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Shine Sprite", 0x49e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Star Piece", 0x49e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Thunder Rage", 0x49e37d),
    LocationData("Keelhaul Key Jungle Bridge: Coconut 1", 0x49e37d),
    LocationData("Keelhaul Key Jungle Bridge: Coconut 2", 0x49e37d),
    LocationData("Keelhaul Key Jungle Bridge: Ice Power", 0x49e37d),
    LocationData("Keelhaul Key Jungle Bridge: Inn Coupon", 0x49e37d),
    LocationData("Keelhaul Key Jungle Bridge: Shine Sprite", 0x49e37d),
    LocationData("Keelhaul Key Grotto Entrance: Bobbery", 0x49e37d),
    LocationData("Keelhaul Key Grotto Entrance: Skull Gem", 0x49e37d),
    LocationData("Keelhaul Key Grotto Entrance: Spite Pouch", 0x49e37d),
    LocationData("Keelhaul Key Grotto Entrance: Star Piece", 0x49e37d),
    LocationData("Keelhaul Key Grotto Entrance: Wedding Ring", 0x49e37d)
]

pirates_grotto: typing.List[LocationData] = [
    LocationData("Pirate's Grotto Entrance: Ruin Powder", 0x49e3a6),
    LocationData("Pirate's Grotto Gate Handle Room: Gate Handle", 0x49e3a6),
    LocationData("Pirate's Grotto Gate Handle Room: Shine Sprite", 0x49e3a6),
    LocationData("Pirate's Grotto Gate Handle Room: Star Piece", 0x49e3a6),
    LocationData("Pirate's Grotto Sluice Gate: Star Piece", 0x49e3a6),
    LocationData("Pirate's Grotto Storeroom: Grotto Key", 0x49e3a6),
    LocationData("Pirate's Grotto Storeroom: Shine Sprite", 0x49e3a6),
    LocationData("Pirate's Grotto Storeroom: Star Piece", 0x49e3a6),
    LocationData("Pirate's Grotto Staircase: Coin", 0x49e3a6),
    LocationData("Pirate's Grotto Staircase: Defend Plus P", 0x49e3a6),
    LocationData("Pirate's Grotto Staircase: Shine Sprite", 0x49e3a6),
    LocationData("Pirate's Grotto Parabuzzy Room: Star Piece", 0x49e3a6),
    LocationData("Pirate's Grotto Chest Boat: Black Key 4", 0x49e3a6),
    LocationData("Pirate's Grotto Chest Boat: Boat Curse", 0x49e3a6),
    LocationData("Pirate's Grotto Chest Boat: P-Down D-Up", 0x49e3a6),
    LocationData("Pirate's Grotto Barrel Room: 10 Coins", 0x49e3a6),
    LocationData("Pirate's Grotto Barrel Room: Shine Sprite", 0x49e3a6),
    LocationData("Pirate's Grotto Spike Wall Room: Shine Sprite", 0x49e3a6),
    LocationData("Pirate's Grotto Cortez' Hoard: Sapphire Star", 0x49e3a6)
]

excess_express: typing.List[LocationData] = [
    LocationData("Excess Express Locomotive: Autograph", 0x49e51e),
    LocationData("Excess Express Locomotive: Star Piece", 0x49e526),
    LocationData("Excess Express Front Passenger Car: Vital Paper", 0x49e52e),
    LocationData("Excess Express Front Passenger Car: 30 Coins", 0x49e52e),
    LocationData("Excess Express Middle Passenger Car: Blanket", 0x49e53b),
    LocationData("Excess Express Middle Passenger Car: Briefcase", 0x49e53b),
    LocationData("Excess Express Middle Passenger Car: Dried Shroom", 0x49e53b),
    LocationData("Excess Express Middle Passenger Car: Galley Pot", 0x49e53b),
    LocationData("Excess Express Middle Passenger Car: Gold Ring", 0x49e53b),
    LocationData("Excess Express Middle Passenger Car: Shell Earrings", 0x49e53b),
    LocationData("Excess Express Middle Passenger Car: Shine Sprite", 0x49e53b),
    LocationData("Excess Express Middle Passenger Car: Star Piece", 0x49e53b),
    LocationData("Excess Express Dining Car: Boo's Sheet", 0x49e53b),
    LocationData("Excess Express Dining Car: Maple Syrup", 0x49e53b),
    LocationData("Excess Express Dining Car: Mystery", 0x49e53b),
    LocationData("Excess Express Dining Car: Star Piece 1", 0x49e53b),
    LocationData("Excess Express Dining Car: Star Piece 2", 0x49e53b),
    LocationData("Excess Express Dining Car: Super Shroom", 0x49e53b),
    LocationData("Excess Express Dining Car: Tasty Tonic", 0x49e53b),
    LocationData("Excess Express Dining Car: Thunder Rage", 0x49e53b),
    LocationData("Excess Express Back Passenger Car: Mushroom", 0x49e53b),
    LocationData("Excess Express Back Passenger Car: Shine Sprite", 0x49e53b),
    LocationData("Excess Express Back Passenger Car: Star Piece", 0x49e53b),
    LocationData("Excess Express Storage Car: Ragged Diary", 0x49e53b)
]

riverside: typing.List[LocationData] = [
    LocationData("Riverside Station Drawbridge: Station Key 1", 0x49e5fd),
    LocationData("Riverside Station Entrance: Close Call P", 0x49e66b),
    LocationData("Riverside Station Clockwork Room: Star Piece", 0x49e66b),
    LocationData("Riverside Station Clockwork Room: Station Key 2", 0x49e66b),
    LocationData("Riverside Station Back Exterior: HP Plus", 0x49e66b),
    LocationData("Riverside Station Back Exterior: Shine Sprite", 0x49e66b),
    LocationData("Riverside Station Back Exterior: Thunder Rage", 0x49e66b),
    LocationData("Riverside Station Tube Mode Maze: Dried Shroom", 0x49e66b),
    LocationData("Riverside Station Tube Mode Maze: P-Up D-Down", 0x49e66b),
    LocationData("Riverside Station Ultra Boots Room: Elevator Key", 0x49e66b),
    LocationData("Riverside Station Ultra Boots Room: Ultra Boots", 0x49e66b),
    LocationData("Riverside Station Goomba Room: Shine Sprite", 0x49e66b)
]

poshley_heights: typing.List[LocationData] = [
    LocationData("Poshley Heights Station: Goldbob Guide", 0x49ea1c),
    LocationData("Poshley Heights Station: HP Drain P", 0x49ea1c),
    LocationData("Poshley Heights Station: Star Piece 1", 0x49ea1c),
    LocationData("Poshley Heights Station: Star Piece 2", 0x49ea1c),
    LocationData("Poshley Heights Station: Star Piece 3", 0x49ea1c),
    LocationData("Poshley Heights Sanctum Exterior: Shine Sprite", 0x49ea1c),
    LocationData("Poshley Heights Sanctum Altar: Garnet Star", 0x49ea1c),
    LocationData("Poshley Heights Sanctum Altar: L Emblem", 0x49ea1c),
    LocationData("Poshley Heights Sanctum Altar: Shine Sprite", 0x49ea1c),
    LocationData("Poshley Heights Downtown: Fresh Pasta", 0x49ea1c),
    LocationData("Poshley Heights Downtown: Inn Coupon", 0x49ea1c),
    LocationData("Poshley Heights Downtown: Omelette Meal", 0x49ea1c),
    LocationData("Poshley Heights Downtown: Star Piece", 0x49ea1c),
]

fahr_outpost: typing.List[LocationData] = [
    LocationData("Fahr Outpost Entrance: Double Dip P", 0x49e6e5),
    LocationData("Fahr Outpost Entrance: Star Piece", 0x49e6e5),
    LocationData("Fahr Outpost Town Outskirts: Star Piece", 0x49e6e5),
    LocationData("Fahr Outpost Town: Ice Storm", 0x49e6e5),
    LocationData("Fahr Outpost Town: Inn Coupon", 0x49e6e5),
    LocationData("Fahr Outpost Town: Maple Syrup", 0x49e6e5),
    LocationData("Fahr Outpost Town: Ruin Powder", 0x49e6e5),
    LocationData("Fahr Outpost Town: Shine Sprite", 0x49e6e5),
    LocationData("Fahr Outpost Town: Shooting Star", 0x49e6e5),
    LocationData("Fahr Outpost Town: Space Food", 0x49e6e5),
    LocationData("Fahr Outpost Town: Star Piece 1", 0x49e6e5),
    LocationData("Fahr Outpost Town: Star Piece 2", 0x49e6e5),
    LocationData("Fahr Outpost Town: Stopwatch", 0x49e6e5),
    LocationData("Fahr Outpost Town: Super Shroom", 0x49e6e5),
    LocationData("Fahr Outpost West Enemy Room: Shine Sprite", 0x49e6e5),
    LocationData("Fahr Outpost West Enemy Room: Star Piece", 0x49e6e5),
    LocationData("Fahr Outpost East Enemy Room: HP Plus P", 0x49e6e5),
    LocationData("Fahr Outpost East Enemy Room: Star Piece", 0x49e6e5)
]

xnaut_fortress: typing.List[LocationData] = [
    LocationData("Moon Landing Site: Stopwatch", 0x49e70f),
    LocationData("Moon Fortress View: Power Punch", 0x49e717),
    LocationData("Moon Fortress View: Star Piece", 0x49e717),
    LocationData("Moon West Room 2: Ruin Powder", 0x49e717),
    LocationData("Moon West Room 1: Courage Shell", 0x49e717),
    LocationData("X-Naut Fortress Elevator Key Room: Elevator Key 1", 0x49e71f),
    LocationData("X-Naut Fortress Elevator Key Room: Super Shroom", 0x49e71f),
    LocationData("X-Naut Fortress Crane Room: Coin 1", 0x49e71f),
    LocationData("X-Naut Fortress Crane Room: Coin 2", 0x49e71f),
    LocationData("X-Naut Fortress Crane Room: Coin 3", 0x49e71f),
    LocationData("X-Naut Fortress Crane Room: Coin 4", 0x49e71f),
    LocationData("X-Naut Fortress Crane Room: Coin 5", 0x49e71f),
    LocationData("X-Naut Fortress Crane Room: Coin 6", 0x49e71f),
    LocationData("X-Naut Fortress Crane Room: Feeling Fine", 0x49e71f),
    LocationData("X-Naut Fortress Crane Room: Feeling Fine P", 0x49e71f),
    LocationData("X-Naut Fortress Crane Room: Star Piece", 0x49e71f),
    LocationData("X-Naut Fortress Quiz Room: Elevator Key 2", 0x49e71f),
    LocationData("X-Naut Fortress Card Key Room A: Card Key 1", 0x49e71f),
    LocationData("X-Naut Fortress Card Key Room A: Sleepy Sheep", 0x49e71f),
    LocationData("X-Naut Fortress Teleporter Room: Cog", 0x49e71f),
    LocationData("X-Naut Fortress Ceiling Grate Room: Star Piece", 0x49e71f),
    LocationData("X-Naut Fortress Office: Card Key 2", 0x49e71f),
    LocationData("X-Naut Fortress Card Key Room B: Card Key 3", 0x49e71f),
    LocationData("X-Naut Fortress Factory: Card Key 4", 0x49e71f),
    LocationData("X-Naut Fortress Factory: Ultra Shroom", 0x49e71f),
    LocationData("X-Naut Fortress Boss Room: Crystal Star", 0x49e71f),
]

palace: typing.List[LocationData] = [
    LocationData("Palace of Shadow Swoopula Staircase: Stopwatch", 0x49e5a0),
    LocationData("Palace of Shadow Bullet Bill Hallway: Shooting Star", 0x49e5a0),
    LocationData("Palace of Shadow Spike Trap Room: All or Nothing", 0x49e5a0),
    LocationData("Palace of Shadow Fire Trap Room: Boo's Sheet", 0x49e5a0),
    LocationData("Palace of Shadow Dark Bones Room: Palace Key", 0x49e55b),
    LocationData("Palace of Shadow Second Bullet Bill Hallway: Ultra Shroom", 0x49e55b),
    LocationData("Palace of Shadow Large Open Room: Coin", 0x49e55b),
    LocationData("Palace of Shadow Large Open Room: Jammin' Jelly", 0x49e55b),
    LocationData("Palace of Shadow Large Open Room: P-Up D-Down P", 0x49e55b),
    LocationData("Riddle Tower Floor 1 NW: Palace Key (Riddle Tower)", 0x49e55b),
    LocationData("Riddle Tower Floor 1 NE: Palace Key (Riddle Tower)", 0x49e55b),
    LocationData("Riddle Tower Floor 1 SW: Palace Key (Riddle Tower)", 0x49e55b),
    LocationData("Riddle Tower Floor 1 SE: Palace Key (Riddle Tower)", 0x49e55b),
    LocationData("Riddle Tower Floor 2 NW: Palace Key (Riddle Tower)", 0x49e55b),
    LocationData("Riddle Tower Floor 2 NE: Palace Key (Riddle Tower)", 0x49e55b),
    LocationData("Riddle Tower Floor 2 SW: Palace Key (Riddle Tower)", 0x49e55b),
    LocationData("Riddle Tower Floor 2 SE: Palace Key (Riddle Tower)", 0x49e55b)
]

riddle_tower: typing.List[LocationData] = [
    LocationData("Palace of Shadow Far Hallway 1: Thunder Rage", 0x49e563),
    LocationData("Palace of Shadow Far Backroom 1: Life Shroom", 0x49e563),
    LocationData("Palace of Shadow Far Backroom 1: Repel Cape", 0x49e563),
    LocationData("Palace of Shadow Far Backroom 2: Life Shroom", 0x49e563),
    LocationData("Palace of Shadow Far Backroom 2: Palace Key", 0x49e563),
    LocationData("Palace of Shadow Far Backroom 2: Shooting Star", 0x49e563),
    LocationData("Palace of Shadow Far Backroom 3: Coin", 0x49e563),
    LocationData("Palace of Shadow Far Backroom 3: Palace Key", 0x49e563),
    LocationData("Palace of Shadow Far Backroom 3: Point Swap", 0x49e563),
    LocationData("Palace of Shadow Far Hallway 4: Life Shroom", 0x49e563),
    LocationData("Palace of Shadow Far Hallway 4: Shooting Star", 0x49e563),
    LocationData("Palace of Shadow Gloomtail Room: Jammin' Jelly", 0x49e563),
    LocationData("Palace of Shadow Gloomtail Room: Star Key", 0x49e563),
    LocationData("Palace of Shadow Gloomtail Room: Ultra Shroom", 0x49e563),
    LocationData("Palace of Shadow Final Staircase: Jammin' Jelly", 0x49e563),
    LocationData("Palace of Shadow Final Staircase: Ultra Shroom", 0x49e563)
]

pit: typing.List[LocationData] = [
    LocationData("Pit of 100 Trials Floor 10: Sleepy Stomp", 0x49e563),
    LocationData("Pit of 100 Trials Floor 20: Fire Drive", 0x49e563),
    LocationData("Pit of 100 Trials Floor 30: Zap Tap", 0x49e563),
    LocationData("Pit of 100 Trials Floor 40: Pity Flower", 0x49e563),
    LocationData("Pit of 100 Trials Floor 50: Strange Sack", 0x49e563),
    LocationData("Pit of 100 Trials Floor 60: Double Dip", 0x49e563),
    LocationData("Pit of 100 Trials Floor 70: Double Dip P", 0x49e563),
    LocationData("Pit of 100 Trials Floor 80: Bump Attack", 0x49e563),
    LocationData("Pit of 100 Trials Floor 90: Lucky Day", 0x49e563),
    LocationData("Pit of 100 Trials Floor 100: Return Postage", 0x49e563),
    LocationData("Pit of 100 Trials Charlieton: Fire Flower", 0x49e563),
    LocationData("Pit of 100 Trials Charlieton: Honey Syrup", 0x49e563),
    LocationData("Pit of 100 Trials Charlieton: Maple Syrup", 0x49e563),
    LocationData("Pit of 100 Trials Charlieton: Mushroom", 0x49e563),
    LocationData("Pit of 100 Trials Charlieton: Super Shroom", 0x49e563),
    LocationData("Pit of 100 Trials Charlieton: Thunder Rage", 0x49e563)
]

all_locations: typing.List[LocationData] = (rogueport + sewers + petal_left + petal_right + hooktails_castle + boggly_woods +
                                            great_tree + glitzville + twilight_town + twilight_trail + creepy_steeple +
                                            pirates_grotto + keelhaul_key + excess_express + riverside + poshley_heights +
                                            fahr_outpost + xnaut_fortress + palace + pit + riddle_tower + rogueport_westside)

location_table: typing.Dict[str, int] = {locData.name: locData.id for locData in all_locations}
