import typing

from BaseClasses import Location


class LocationData:
    name: str = ""
    id: int = 0x00

    def __init__(self, name, id_):
        self.name = name
        self.id = id_


class TTYDLocation(Location):
    game: str = "Mario & Luigi Superstar Saga"


rogueport: typing.List[LocationData] = [
    LocationData("Rogueport Docks: HP Drain", 0x39d65d),
    LocationData("Rogueport Docks: Star Piece", 0x39d665),
    LocationData("Rogueport Center: Goombella", 0x39d678),
    LocationData("Rogueport Center: Contact Lens", 0x39d6ad),
    LocationData("Rogueport Center: Old Letter", 0x39d6ca),
    LocationData("Rogueport Center: Attack FX G", 0x39d6c2),
    LocationData("Rogueport Center: Attack FX P", 0x39d6ba),
    LocationData("Rogueport Center: Boo's Sheet", 0x39d713),
    LocationData("Rogueport Center: Close Call", 0x39d731),
    LocationData("Rogueport Center: Close Call P", 0x39d873),
    LocationData("Rogueport Center: Damage Dodge", 0x39d87b),
    LocationData("Rogueport Center: Damage Dodge P", 0x39d883),
    LocationData("Rogueport Center: Double Pain", 0x39d890),
    LocationData("Rogueport Center: Dried Shroom", 0x39d8a0),
    LocationData("Rogueport Center: Earthquake", 0x39d8ad),
    LocationData("Rogueport Center: Fire Drive", 0x39d8b5),
    LocationData("Rogueport Center: Fire Flower", 0x39d8d2),
    LocationData("Rogueport Center: First Attack", 0x39d8f2),
    LocationData("Rogueport Center: FP Drain", 0x39d8fa),
    LocationData("Rogueport Center: Fright Mask", 0x39d91c),
    LocationData("Rogueport Center: Hammerman", 0x39d924),
    LocationData("Rogueport Center: Happy Flower", 0x39d92c),
    LocationData("Rogueport Center: Head Rattle", 0x39d939),
    LocationData("Rogueport Center: Honey Syrup", 0x39d957),
    LocationData("Rogueport Center: Ice Smash", 0x39d96f),
    LocationData("Rogueport Center: Jammin' Jelly", 0x39d97f),
    LocationData("Rogueport Center: Jumpman", 0x39d98f),
    LocationData("Rogueport Center: Last Stand", 0x39d99c),
    LocationData("Rogueport Center: Last Stand P", 0x39d9a4),
    LocationData("Rogueport Center: Mega Rush", 0x39d9ac),
    LocationData("Rogueport Center: Mushroom", 0x39d9b4),
    LocationData("Rogueport Center: Piercing Blow", 0x39d9bc),
    LocationData("Rogueport Center: Power Jump", 0x39d9c9),
    LocationData("Rogueport Center: Power Rush", 0x39d9d1),
    LocationData("Rogueport Center: Power Rush P", 0x39d9d9),
    LocationData("Rogueport Center: Pretty Lucky P", 0x39d9e1),
    LocationData("Rogueport Center: Repel Cape", 0x39d9fe),
    LocationData("Rogueport Center: Shooting Star", 0x39d9f6),
    LocationData("Rogueport Center: Shrink Stomp", 0x39da35),
    LocationData("Rogueport Center: Simplifier", 0x39da2d),
    LocationData("Rogueport Center: Simplifier (6 Chapters Cleared)", 0x39da77),
    LocationData("Rogueport Center: Sleepy Sheep", 0x39da7f),
    LocationData("Rogueport Center: Sleepy Stomp", 0x39dacd),
    LocationData("Rogueport Center: Slow Go", 0x39da98),
    LocationData("Rogueport Center: Soft Stomp", 0x39daad),
    LocationData("Rogueport Center: Star Piece 1", 0x39dd03),
    LocationData("Rogueport Center: Star Piece 2", 0x39e13d),
    LocationData("Rogueport Center: Star Piece 3", 0x39e145),
    LocationData("Rogueport Center: Star Piece 4", 0x39e14d),
    LocationData("Rogueport Center: Star Piece 5", 0x39e15a),
    LocationData("Rogueport Center: Stopwatch", 0x39e162),
    LocationData("Rogueport Center: Super Appeal", 0x39e1f0),
    LocationData("Rogueport Center: Super Appeal P", 0x39e1f8),
    LocationData("Rogueport Center: Tasty Tonic", 0x39e200),
    LocationData("Rogueport Center: Timing Tutor", 0x39e8f5),
    LocationData("Rogueport Center: Ultra Hammer", 0x39e912),
    LocationData("Rogueport Center: Ultra Shroom", 0x39e9b5),
    LocationData("Rogueport Center: Unsimplifier", 0x3c05f0),
    LocationData("Rogueport Center: Unsimplifier (6 Chapters Cleared)", 0x3c05f2),
    LocationData("Rogueport Center: W Emblem", 0x3c05f4),
    LocationData("Rogueport Eastside: Power Smash", 0x39d85e),
    LocationData("Rogueport Eastside: Double Dip", 0x39d86b),
    LocationData("Rogueport Eastside: Shine Sprite 1", 0x39d898),
    LocationData("Rogueport Eastside: Shine Sprite 2", 0x39d8bd),
    LocationData("Rogueport Eastside: Star Piece 1", 0x39d8c5),
    LocationData("Rogueport Eastside: Star Piece 2", 0x39d8e2),
    LocationData("Rogueport Eastside: Star Piece 3", 0x39d907),
    LocationData("Rogueport Eastside: Star Piece 4", 0x39d90f),
    LocationData("Rogueport Eastside: Star Piece 5", 0x39d941),
]

rogueport_westside: typing.List[LocationData] = [
    LocationData("Rogueport Westside: Blimp Ticket", 0x39d95f),
    LocationData("Rogueport Westside: Train Ticket", 0x39db02),
    LocationData("Rogueport Westside: Cake Mix", 0x39daea),
    LocationData("Rogueport Westside: Dizzy Dial", 0x39dab5),
    LocationData("Rogueport Westside: Dried Shroom", 0x39db0f),
    LocationData("Rogueport Westside: FP Plus", 0x39db22),
    LocationData("Rogueport Westside: Gold Bar x3", 0x39db2a),
    LocationData("Rogueport Westside: Hammer Throw", 0x39db32),
    LocationData("Rogueport Westside: HP Plus", 0x39db87),
    LocationData("Rogueport Westside: HP Plus P", 0x39db97),
    LocationData("Rogueport Westside: Jammin' Jelly", 0x39dbac),
    LocationData("Rogueport Westside: Life Shroom", 0x39dbb4),
    LocationData("Rogueport Westside: Lottery Pick", 0x39dbbc),
    LocationData("Rogueport Westside: Mushroom", 0x39dbc9),
    LocationData("Rogueport Westside: Power Jump", 0x39dbd9),
    LocationData("Rogueport Westside: Power Rush", 0x39dbe1),
    LocationData("Rogueport Westside: Power Rush P", 0x39dbee),
    LocationData("Rogueport Westside: Power Smash", 0x39dbfb),
    LocationData("Rogueport Westside: Quake Hammer", 0x39dc08),
    LocationData("Rogueport Westside: Refund", 0x39dc20),
    LocationData("Rogueport Westside: Shine Sprite 1", 0x39dc28),
    LocationData("Rogueport Westside: Shine Sprite 2", 0x39dc4d),
    LocationData("Rogueport Westside: Star Piece 1", 0x39dc7a),
    LocationData("Rogueport Westside: Star Piece 2", 0x39dc82),
    LocationData("Rogueport Westside: Star Piece 3", 0x39dc8f),
    LocationData("Rogueport Westside: Star Piece 4", 0x39dc97),
    LocationData("Rogueport Westside: Super Appeal", 0x39dc9f),
    LocationData("Rogueport Westside: Super Shroom 1", 0x39dcac),
    LocationData("Rogueport Westside: Super Shroom 2", 0x39dcbc),
    LocationData("Rogueport Westside: Thunder Bolt", 0x39dcc4),
    LocationData("Rogueport Westside: Tornado Jump", 0x39dcd1),
    LocationData("Rogueport Westside: Ultra Shroom 1", 0x39dce1),
    LocationData("Rogueport Westside: Ultra Shroom 2", 0x39dcd9),
    LocationData("Rogueport Westside: Volt Shroom", 0x39dcee),
    LocationData("Rogueport Blimp Room: Star Piece 1", 0x39e17f),
    LocationData("Rogueport Blimp Room: Star Piece 2", 0x39e187)
]

sewers: typing.List[LocationData] = [
    LocationData("Rougueport Sewers Town: Attack FX Y", 0x39da42),
    LocationData("Rougueport Sewers Town: Chill Out", 0x39da4a),
    LocationData("Rougueport Sewers Town: Flower Finder", 0x39da52),
    LocationData("Rougueport Sewers Town: Flower Saver", 0x39d9e9),
    LocationData("Rougueport Sewers Town: Flower Saver P", 0x277a45),
    LocationData("Rougueport Sewers Town: Gold Bar", 0x39e5b5),
    LocationData("Rougueport Sewers Town: Gold Bar x3", 0x39e5c8),
    LocationData("Rougueport Sewers Town: Gradual Syrup", 0x39e5d0),
    LocationData("Rougueport Sewers Town: Happy Flower", 0x39da0b),
    LocationData("Rougueport Sewers Town: Happy Heart", 0x39da20),
    LocationData("Rougueport Sewers Town: Happy Heart P", 0x39da18),
    LocationData("Rougueport Sewers Town: Heart Finder", 0x39da42),
    LocationData("Rougueport Sewers Town: Item Hog", 0x39da4a),
    LocationData("Rougueport Sewers Town: Jammin' Jelly", 0x39da52),
    LocationData("Rougueport Sewers Town: Peekaboo", 0x39d9e9),
    LocationData("Rougueport Sewers Town: Power Plus", 0x277a45),
    LocationData("Rougueport Sewers Town: Power Plus P", 0x39e5b5),
    LocationData("Rougueport Sewers Town: Pretty Lucky", 0x39e5c8),
    LocationData("Rougueport Sewers Town: Quick Change", 0x39e5d0),
    LocationData("Rougueport Sewers Town: Shine Sprite", 0x39da0b),
    LocationData("Rougueport Sewers Town: Slow Shroom", 0x39da20),
    LocationData("Rougueport Sewers Town: Soft Stomp", 0x39da42),
    LocationData("Rougueport Sewers Town: Star Piece 1", 0x39da4a),
    LocationData("Rougueport Sewers Town: Star Piece 2", 0x39da52),
    LocationData("Rougueport Sewers Town: Star Piece 3", 0x39d9e9),
    LocationData("Rougueport Sewers Town: Star Piece 4", 0x277a45),
    LocationData("Rougueport Sewers East Entrance: Ultra Mushroom", 0x39e5b5),
    LocationData("Rougueport Sewers East Entrance: Star Piece", 0x39e5c8),
    LocationData("Rougueport Sewers Petal Meadows Pipe: Shine Sprite", 0x39e5d0),
    LocationData("Rogueport Sewers Boggly Woods Pipe: Damage Dodge", 0x39da0b),
    LocationData("Rogueport Sewers Boggly Woods Pipe: Star Piece", 0x39da20),
    LocationData("Rogueport Sewers Black Key Room: Black Key", 0x39da42),
    LocationData("Rogueport Sewers Black Key Room: Happy Heart P", 0x39da4a),
    LocationData("Rogueport Sewers Black Key Room: Pretty Lucky", 0x39da52),
    LocationData("Rogueport Sewers Black Key Room: Star Piece", 0x39d9e9),
    LocationData("Rogueport Sewers Thousand Year Door: Shine Sprite", 0x277a45),
    LocationData("Rogueport Sewers Thousand Year Door: Star Piece", 0x39e5b5),
    LocationData("Rougueport Sewers Pit Entrance: Star Piece", 0x39e5c8),
    LocationData("Rogueport Sewers West Entrance: Flower Saver P", 0x39e5d0),
    LocationData("Rogueport Sewers West Entrance: Shine Sprite", 0x39da0b),
    LocationData("Rogueport Sewers West Entrance: Star Piece 1", 0x39da20),
    LocationData("Rogueport Sewers West Entrance: Star Piece 2", 0x39da42),
    LocationData("Rogueport Sewers East Enemy Hall: Fire Flower", 0x39da4a),
    LocationData("Rogueport Sewers East Enemy Hall: Mushroom", 0x39da52),
    LocationData("Rogueport Sewers East Pipe Room: Shine Sprite", 0x39d9e9),
    LocationData("Rogueport Sewers West Pipe Room: FP Plus", 0x277a45),
    LocationData("Rogueport Sewers West Enemy Hall: Gradual Syrup", 0x39e5b5),
    LocationData("Rogueport Sewers West Enemy Hall: Slow Shroom", 0x39e5c8),
    LocationData("Rogueport Sewers Black Chest Room: Plane Curse", 0x39e5d0),
    LocationData("Rogueport Sewers Black Chest Room: Star Piece", 0x39da0b),
    LocationData("Rogueport Sewers Spania Room: Defend Plus", 0x39da20),
    LocationData("Rogueport Sewers Spania Room: Shine Sprite 1", 0x39da42),
    LocationData("Rogueport Sewers Spania Room: Shine Sprite 2", 0x39da4a),
    LocationData("Rogueport Sewers Spania Room: Shine Sprite 3", 0x39da52),
    LocationData("Rogueport Sewers Spike Room: Spike Shield", 0x39d9e9)
]

petal_right: typing.List[LocationData] = [
    LocationData("Petal Meadows Bridge Room: Coin 2", 0x39e22a),
    LocationData("Petal Meadows Bridge Room: Fire Flower", 0x39e232),
    LocationData("Petal Meadows Bridge Room: Mystery", 0x39e23f),
    LocationData("Petal Meadows First Fort Exterior: Coin 1", 0x39e254),
    LocationData("Petal Meadows First Fort Exterior: Coin 2", 0x39e261),
    LocationData("Petal Meadows First Fort Exterior: POW Block", 0x39e269),
    LocationData("Petal Meadows Second Fort Exterior: Coin", 0x39e271),
    LocationData("Petal Meadows Second Fort Exterior: Fire Flower", 0x39e279),
    LocationData("Petal Meadows Second Fort Exterior: Inn Coupon", 0x39e8fd),
    LocationData("Petal Meadows Sewers West Key Room: Moon Stone", 0x39e90a),
    LocationData("Petal Meadows Sewers: Multibounce", 0x39e91a),
    LocationData("Petal Meadows Sewers East Key Room: Sun Stone", 0x1e9411),
    LocationData("Petalburg Westside: Courage Shell", 0x22913a),
    LocationData("Petalburg Westside: Fire Flower", 0x22890e),
    LocationData("Petalburg Westside: Honey Syrup", 0x228775),
    LocationData("Petalburg Westside: Mr. Softener", 0x1e9431),
    LocationData("Petalburg Westside: Mushroom", 0x277ab2),
    LocationData("Petalburg Westside: POW Block", 0x2779C8),
    LocationData("Petalburg Westside: Star Piece", 0x1E9430),
    LocationData("Petalburg Eastside: Mega Rush P", 0x1E9404),
    LocationData("Petalburg Eastside: Star Piece", 0x1e9405),
    LocationData("Petalburg Eastside: Turtley Leaf", 0x1e9435)
]

petal_left: typing.List[LocationData] = [
    LocationData("Petal Meadows Entrance: Mushroom 1", 0x39e1d6),
    LocationData("Petal Meadows Entrance: Mushroom 2", 0x39e1e3),
    LocationData("Petal Meadows Entrance: Star Piece", 0x39e208),
    LocationData("Petal Meadows Bridge Room: Koops", 0x39e210),
    LocationData("Petal Meadows Bridge Room: Coin 1", 0x39e21d),
    LocationData("Petal Meadows Bridge Room: Star Piece", 0x39e24c),
    LocationData("Petal Meadows Field: 10 Coins", 0x1e9412),
    LocationData("Petal Meadows Field: Close Call", 0x229345),
    LocationData("Petal Meadows Field: Happy Heart", 0x22954d),
    LocationData("Petal Meadows Field: Horsetail", 0x228a17)
]

hooktails_castle: typing.List[LocationData] = [
    LocationData("Hooktail's Castle Drawbridge: HP Plus", 0x39d680),
    LocationData("Hooktail's Castle Entrance: Power Bounce", 0x39d688),
    LocationData("Hooktail's Castle Red Bones Room: Castle Key", 0x39d690),
    LocationData("Hooktail's Castle Red Bones Room: Star Piece", 0x39d69d),
    LocationData("Hooktail's Castle Stair Switch Room: Castle Key", 0x39d6a5),
    LocationData("Hooktail's Castle Stair Switch Room: Shine Sprite", 0x39d6d7),
    LocationData("Hooktail's Castle Stair Switch Room: Star Piece 1", 0x39d6df),
    LocationData("Hooktail's Castle Stair Switch Room: Star Piece 1", 0x39d70b),
    LocationData("Hooktail's Castle Stair Central Staircase: Castle Key", 0x39d71b),
    LocationData("Hooktail's Castle Stair Central Staircase: Last Stand P", 0x39d803),
    LocationData("Hooktail's Castle Stair Central Staircase: Shine Sprite", 0x39d8da),
    LocationData("Hooktail's Castle Stair Central Staircase: Star Piece", 0x39d977),
    LocationData("Hooktail's Castle Prison Entrance: Paper Curse", 0x39d987),
    LocationData("Hooktail's Castle Prison Entrance: Attack FX R", 0x39daa0),
    LocationData("Hooktail's Castle Spikes Room: Black Key 2", 0x39dac5),
    LocationData("Hooktail's Castle Life Shroom Room: Life Shroom", 0x39dad5),
    LocationData("Hooktail's Castle Plane Rafters Room: Star Piece", 0x39dae2),
    LocationData("Hooktail's Castle Hooktail's Room: Diamond Star", 0x39daf2),
    LocationData("Hooktail's Castle Storeroom: Castle Key", 0x39dafa),
    LocationData("Hooktail's Castle Storeroom: Honey Syrup", 0x39db8f),
    LocationData("Hooktail's Castle Storeroom: Mushroom", 0x39dc18),
    LocationData("Hooktail's Castle Storeroom: Shine Sprite", 0x39dc3d),
    LocationData("Hooktail's Castle Up Arrow Room: Up Arrow", 0x39dd30)
]

boggly_woods: typing.List[LocationData] = [
    LocationData("Boggly Woods Shadow Sirens Room: Necklace", 0x39e951),
    LocationData("Boggly Woods Shadow Sirens Room: Honey Syrup", 0x39e959),
    LocationData("Boggly Woods Shadow Sirens Room: Sleepy Sheep", 0x1e9441),
    LocationData("Boggly Woods Tree View: Coin", 0x1e9434),
    LocationData("Boggly Woods Tree View: Inn Coupon", 0x1e9444),
    LocationData("Boggly Woods Plane Panel Room: P-Down D-Up P", 0x39dc65),
    LocationData("Boggly Woods Plane Panel Room: Quake Hammer", 0x39dc5d),
    LocationData("Boggly Woods Plane Panel Room: Shine Sprite", 0x39dc45),
    LocationData("Boggly Woods Plane Panel Room: Star Piece", 0x39dc35),
    LocationData("Boggly Woods Outside Flurrie's House: Star Piece 1", 0x1e9434),
    LocationData("Boggly Woods Outside Flurrie's House: Star Piece 2", 0x1e9444),
    LocationData("Boggly Woods Outside Flurrie's House: Volt Shroom", 0x39dc65),
    LocationData("Boggly Woods Flurrie's House: Flurrie", 0x39dc5d),
    LocationData("Boggly Woods Flurrie's House Backroom: Star Piece", 0x39dc45),
    LocationData("Boggly Woods Flurrie's House Backroom: Super Appeal P", 0x39dc35),
    LocationData("Boggly Woods Outside Great Tree: FP Plus", 0x39dc35)
]

great_tree: typing.List[LocationData] = [
    LocationData("Great Tree Entrance: Coin", 0x39dd20),
    LocationData("Great Tree Entrance: Emerald Star", 0x39dd38),
    LocationData("Great Tree Entrance: Mystic Egg", 0x39dd48),
    LocationData("Great Tree Entrance: Puni Orb", 0x39dd50),
    LocationData("Great Tree 10-Puni Pedestal: Star Piece", 0x39dd5d),
    LocationData("Great Tree Red/Blue Cages: Star Piece", 0x39dd6d),
    LocationData("Great Tree Red Key Room: Coin", 0x39dd82),
    LocationData("Great Tree Red Key Room: Mushroom", 0x39dd8a),
    LocationData("Great Tree Red Key Room: Red Key", 0x39dd9f),
    LocationData("Great Tree Red Key Room: Ultra Shroom", 0x39ddac),
    LocationData("Great Tree Bubble Room: Shine Sprite", 0x39ddc1),
    LocationData("Great Tree Bubble Room: Thunder Rage", 0x39ddc9),
    LocationData("Great Tree Zigzag Room: Coin", 0x39ddd6),
    LocationData("Great Tree Zigzag Room: Damage Dodge P", 0x39ddde),
    LocationData("Great Tree Zigzag Room: Star Piece", 0x39ddee),
    LocationData("Great Tree Shop: Honey Syrup", 0x39ddf6),
    LocationData("Great Tree Shop: HP Drain", 0x39de06),
    LocationData("Great Tree Shop: Ice Storm", 0x39de0e),
    LocationData("Great Tree Shop: Mini Mr.Mini", 0x39de16),
    LocationData("Great Tree Shop: Mushroom", 0x39de29),
    LocationData("Great Tree Shop: Mystery", 0x39de39),
    LocationData("Great Tree Red Key Room: Blue Key", 0x39de41),
    LocationData("Great Tree Red Key Room: Charge", 0x39de49),
    LocationData("Great Tree Red Key Room: Shine Sprite", 0x39de56),
    LocationData("Great Tree Super Boots Room: Super Boots", 0x39de66),
    LocationData("Great Tree 100-Puni Pedestal: Coin", 0x39de73),
    LocationData("Great Tree 100-Puni Pedestal: Star Piece", 0x39de7b),
    LocationData("Great Tree Elevator Pedestal: Mushroom", 0x39de83),
    LocationData("Great Tree Escape Ambush Room: Star Piece", 0x39de8b),
    LocationData("Great Tree Pool Room: Dizzy Dial", 0x39de98),
    LocationData("Great Tree Pool Room: Shine Sprite", 0x39dea0),
    LocationData("Great Tree Pool Room: Shrink Stomp", 0x39dea8),
    LocationData("Great Tree Fake Pedestal: Star Piece", 0x39deb5),
    LocationData("Great Tree Lower Duplex: Coin", 0x39dec2),
    LocationData("Great Tree Middel Duplex: Shine Sprite", 0x39decf),
    LocationData("Great Tree Upper Duplex: Power Punch", 0x39ded7)
]

glitzville: typing.List[LocationData] = [
    LocationData("Glitzville Main Square: Coin", 0x39d7a4),
    LocationData("Glitzville Main Square: Earth Quake", 0x39d7a4),
    LocationData("Glitzville Main Square: Hot Dog", 0x39d7a4),
    LocationData("Glitzville Main Square: Inn Coupon", 0x39d7a4),
    LocationData("Glitzville Main Square: Point Swap", 0x39d7a4),
    LocationData("Glitzville Main Square: Power Plus P", 0x39d7a4),
    LocationData("Glitzville Main Square: Power Punch", 0x39d7a4),
    LocationData("Glitzville Main Square: Repel Cape", 0x39d7a4),
    LocationData("Glitzville Main Square: Shine Sprite", 0x39d7a4),
    LocationData("Glitzville Main Square: Star Piece 1", 0x39d7a4),
    LocationData("Glitzville Main Square: Star Piece 2", 0x39d7a4),
    LocationData("Glitzville Main Square: Star Piece 3", 0x39d7a4),
    LocationData("Glitzville Main Square: Star Piece 4", 0x39d7a4),
    LocationData("Glitzville Main Square: Star Piece 5", 0x39d7a4),
    LocationData("Glitzville Main Square: Storage Key 1", 0x39d7a4),
    LocationData("Glitzville Main Square: Super Hammer", 0x39d7a4),
    LocationData("Glitzville Main Square: Super Shroom", 0x39d7a4),
    LocationData("Glitzville Main Square: Thunder Bolt", 0x39d7a4),
    LocationData("Glitzville Lobby: Star Piece", 0x39d7ac),
    LocationData("Glitzville Lobby: Storage Key 2", 0x39d7b4),
    LocationData("Glitzville Arena: Gold Star", 0x39d7bc),
    LocationData("Glitzville Hall: Last Stand", 0x39d7d8),
    LocationData("Glitzville Promoter's Office: Star Piece 1", 0x39d7e0),
    LocationData("Glitzville Promoter's Office: Star Piece 2", 0x39d7e8),
    LocationData("Glitzville Storage Room: Charge P", 0x39d7f0),
    LocationData("Glitzville Storage Room: HP Plus P", 0x39d7f0),
    LocationData("Glitzville Storage Room: Shine Sprite", 0x39d7f0),
    LocationData("Glitzville Storage Room: Star Piece", 0x39d7f0),
    LocationData("Glitzville Major-League Room: Champ's Belt", 0x1e9433),
    LocationData("Glitzville Major-League Room: Ice Storm", 0x1e9433),
    LocationData("Glitzville Minor-League Room: Dubious Paper", 0x1e9432),
    LocationData("Glitzville Minor-League Room: Yoshi", 0x1e9432),
    LocationData("Glitzville Storage Back Room: Star Piece", 0x251347)
]

twilight_town: typing.List[LocationData] = [
    LocationData("Twilight Town Leftside: Coin", 0x39e16f),
    LocationData("Twilight Town Leftside: Peachy Peach", 0x39e16f),
    LocationData("Twilight Town Leftside: Star Piece 1", 0x39e16f),
    LocationData("Twilight Town Leftside: Star Piece 2", 0x39e16f),
    LocationData("Twilight Town Leftside: Superbombomb", 0x39e16f),
    LocationData("Twilight Town Leftside: Vivian", 0x39e16f),
    LocationData("Twilight Town Rightside: Boo's Sheet", 0x39e194),
    LocationData("Twilight Town Rightside: Defend Plus", 0x39e194),
    LocationData("Twilight Town Rightside: Inn Coupon", 0x39e194),
    LocationData("Twilight Town Rightside: Jammin' Jelly", 0x39e194),
    LocationData("Twilight Town Rightside: Life Shroom 1", 0x39e194),
    LocationData("Twilight Town Rightside: Life Shroom 2", 0x39e194),
    LocationData("Twilight Town Rightside: Maple Syrup", 0x39e194),
    LocationData("Twilight Town Rightside: Spite Pouch", 0x39e194),
    LocationData("Twilight Town Rightside: Star Piece", 0x39e194),
    LocationData("Twilight Town Rightside: Stopwatch", 0x39e194),
    LocationData("Twilight Town Rightside: Super Shroom", 0x39e194),
    LocationData("Twilight Town Rightside: Thunder Rage", 0x39e194),
    LocationData("Twilight Town Rightside: Tube Curse", 0x39e194)
]

twilight_trail: typing.List[LocationData] = [
    LocationData("Twilight Trail Entrance: 10 Coins", 0x39e0a5),
    LocationData("Twilight Trail Entrance: Black Key 3", 0x39e0ad),
    LocationData("Twilight Trail Hyper Goomba Room: 10 Coins", 0x39e0b5),
    LocationData("Twilight Trail Hyper Goomba Room: Coin", 0x39e0b5),
    LocationData("Twilight Trail Hyper Goomba Room: Super Shroom", 0x39e0b5),
    LocationData("Twilight Trail Fallen Tree: Shop Key", 0x39e0bd),
    LocationData("Twilight Trail Fallen Tree: Star Piece 1", 0x39e0bd),
    LocationData("Twilight Trail Fallen Tree: Star Piece 2", 0x39e0bd),
    LocationData("Twilight Trail Dark Woods First Room: 10 Coins", 0x39e0c5),
    LocationData("Twilight Trail Dark Woods First Room: Earthquake", 0x39e0c5),
    LocationData("Twilight Trail Dark Woods Second Room: Hammer Throw", 0x39e0cd),
    LocationData("Twilight Trail Dark Woods Third Room: 10 Coins", 0x39e057),
    LocationData("Twilight Trail Dark Woods Third Room: Shine Sprite", 0x39e057),
    LocationData("Twilight Trail Steeple Exterior: Coin", 0x39e0da),
    LocationData("Twilight Trail Steeple Exterior: Star Piece", 0x39e0da)
]

creepy_steeple: typing.List[LocationData] = [
    LocationData("Creepy Steeple Main Hall: Lucky Start", 0x39e2dc),
    LocationData("Creepy Steeple Main Hall: Steeple Key 1", 0x39e2dc),
    LocationData("Creepy Steeple North Hall: Golden Leaf", 0x39e2e9),
    LocationData("Creepy Steeple Upper Room: Ruby Star", 0x39e2f6),
    LocationData("Creepy Steeple Cookbook Room: Cookbook", 0x39e2fe),
    LocationData("Creepy Steeple Cookbook Room: Ice Smash", 0x39e2fe),
    LocationData("Creepy Steeple Cookbook Room: Shine Sprite", 0x39e2fe),
    LocationData("Creepy Steeple Cookbook Room: Star Piece", 0x39e2fe),
    LocationData("Creepy Steeple Under Statue: Flower Saver", 0x39e306),
    LocationData("Creepy Steeple Boo Chest Room: Star Piece", 0x39e30e),
    LocationData("Creepy Steeple Boo Chest Room: Ultra Mushroom", 0x39e30e),
    LocationData("Creepy Steeple Parrot Room: Mr. Softener", 0x39e316),
    LocationData("Creepy Steeple Parrot Room: Power Plus", 0x39e316),
    LocationData("Creepy Steeple Parrot Room: Star Piece", 0x39e316),
    LocationData("Creepy Steeple Parrot Room: Steeple Key 2", 0x39e316),
    LocationData("Creepy Steeple Parrot Room: The Letter \"P\"", 0x39e316),
    LocationData("Creepy Steeple Well Entrance: Shine Sprite", 0x39e323),
    LocationData("Creepy Steeple Buzzy Room: Tornado Jump", 0x39e32b),
    LocationData("Creepy Steeple Underground Tube Passage: Shine Sprite", 0x39e333)
]

keelhaul_key: typing.List[LocationData] = [
    LocationData("Keelhaul Key Landing Site: Star Piece", 0x39e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 1", 0x39e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 2", 0x39e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 3", 0x39e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 4", 0x39e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 5", 0x39e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 6", 0x39e37d),
    LocationData("Keelhaul Key Landing Site: Whacka Bump 7", 0x39e37d),
    LocationData("Keelhaul Key Town: Chuckola Cola", 0x39e37d),
    LocationData("Keelhaul Key Town: Fire Flower", 0x39e37d),
    LocationData("Keelhaul Key Town: Fright Mask", 0x39e37d),
    LocationData("Keelhaul Key Town: Honey Syrup", 0x39e37d),
    LocationData("Keelhaul Key Town: Ice Storm", 0x39e37d),
    LocationData("Keelhaul Key Town: Sleepy Sheep", 0x39e37d),
    LocationData("Keelhaul Key Town: Star Piece 1", 0x39e37d),
    LocationData("Keelhaul Key Town: Star Piece 2", 0x39e37d),
    LocationData("Keelhaul Key Town: Super Shroom", 0x39e37d),
    LocationData("Keelhaul Key Jungle Entrance: Coin", 0x39e37d),
    LocationData("Keelhaul Key Jungle Entrance: Courage Shell", 0x39e37d),
    LocationData("Keelhaul Key Jungle Entrance: Head Rattle", 0x39e37d),
    LocationData("Keelhaul Key Jungle Entrance: Keel Mango", 0x39e37d),
    LocationData("Keelhaul Key Jungle Entrance: Star Piece", 0x39e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: 10 Coins", 0x39e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Coin 1", 0x39e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Coin 2", 0x39e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Jammin' Jelly", 0x39e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Mini Mr.Mini", 0x39e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Shine Sprite", 0x39e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Star Piece", 0x39e37d),
    LocationData("Keelhaul Key Jungle Stupid Room: Thunder Rage", 0x39e37d),
    LocationData("Keelhaul Key Jungle Bridge: Coconut 1", 0x39e37d),
    LocationData("Keelhaul Key Jungle Bridge: Coconut 2", 0x39e37d),
    LocationData("Keelhaul Key Jungle Bridge: Ice Power", 0x39e37d),
    LocationData("Keelhaul Key Jungle Bridge: Inn Coupon", 0x39e37d),
    LocationData("Keelhaul Key Jungle Bridge: Shine Sprite", 0x39e37d),
    LocationData("Keelhaul Key Grotto Entrance: Bobbery", 0x39e37d),
    LocationData("Keelhaul Key Grotto Entrance: Skull Gem", 0x39e37d),
    LocationData("Keelhaul Key Grotto Entrance: Spite Pouch", 0x39e37d),
    LocationData("Keelhaul Key Grotto Entrance: Star Piece", 0x39e37d),
    LocationData("Keelhaul Key Grotto Entrance: Wedding Ring", 0x39e37d)
]

pirates_grotto: typing.List[LocationData] = [
    LocationData("Pirate's Grotto Entrance: Ruin Powder", 0x39e3a6),
    LocationData("Pirate's Grotto Gate Handle Room: Gate Handle", 0x39e3a6),
    LocationData("Pirate's Grotto Gate Handle Room: Shine Sprite", 0x39e3a6),
    LocationData("Pirate's Grotto Gate Handle Room: Star Piece", 0x39e3a6),
    LocationData("Pirate's Grotto Sluice Gate: Star Piece", 0x39e3a6),
    LocationData("Pirate's Grotto Storeroom: Grotto Key", 0x39e3a6),
    LocationData("Pirate's Grotto Storeroom: Shine Sprite", 0x39e3a6),
    LocationData("Pirate's Grotto Storeroom: Star Piece", 0x39e3a6),
    LocationData("Pirate's Grotto Staircase: Coin", 0x39e3a6),
    LocationData("Pirate's Grotto Staircase: Defend Plus P", 0x39e3a6),
    LocationData("Pirate's Grotto Staircase: Shine Sprite", 0x39e3a6),
    LocationData("Pirate's Grotto Parabuzzy Room: Star Piece", 0x39e3a6),
    LocationData("Pirate's Grotto Chest Boat: Black Key 4", 0x39e3a6),
    LocationData("Pirate's Grotto Chest Boat: Boat Curse", 0x39e3a6),
    LocationData("Pirate's Grotto Chest Boat: P-Down D-Up", 0x39e3a6),
    LocationData("Pirate's Grotto Barrel Room: 10 Coins", 0x39e3a6),
    LocationData("Pirate's Grotto Barrel Room: Shine Sprite", 0x39e3a6),
    LocationData("Pirate's Grotto Cortez' Hoard: Sapphire Star", 0x39e3a6)
]

excess_express: typing.List[LocationData] = [
    LocationData("Excess Express Locomotive: Autograph", 0x39e51e),
    LocationData("Excess Express Locomotive: Star Piece", 0x39e526),
    LocationData("Excess Express Front Passenger Car: Vital Paper", 0x39e52e),
    LocationData("Excess Express Front Passenger Car: 30 Coins", 0x39e52e),
    LocationData("Excess Express Middle Passenger Car: Blanket", 0x39e53b),
    LocationData("Excess Express Middle Passenger Car: Briefcase", 0x39e53b),
    LocationData("Excess Express Middle Passenger Car: Dried Shroom", 0x39e53b),
    LocationData("Excess Express Middle Passenger Car: Galley Pot", 0x39e53b),
    LocationData("Excess Express Middle Passenger Car: Gold Ring", 0x39e53b),
    LocationData("Excess Express Middle Passenger Car: Shell Earrings", 0x39e53b),
    LocationData("Excess Express Middle Passenger Car: Shine Sprite", 0x39e53b),
    LocationData("Excess Express Middle Passenger Car: Star Piece", 0x39e53b),
    LocationData("Excess Express Dining Car: Boo's Sheet", 0x39e53b),
    LocationData("Excess Express Dining Car: Maple Syrup", 0x39e53b),
    LocationData("Excess Express Dining Car: Mystery", 0x39e53b),
    LocationData("Excess Express Dining Car: Star Piece 1", 0x39e53b),
    LocationData("Excess Express Dining Car: Star Piece 2", 0x39e53b),
    LocationData("Excess Express Dining Car: Super Shroom", 0x39e53b),
    LocationData("Excess Express Dining Car: Tasty Tonic", 0x39e53b),
    LocationData("Excess Express Dining Car: Thunder Rage", 0x39e53b),
    LocationData("Excess Express Back Passenger Car: Mushroom", 0x39e53b),
    LocationData("Excess Express Back Passenger Car: Shine Sprite", 0x39e53b),
    LocationData("Excess Express Back Passenger Car: Star Piece", 0x39e53b),
    LocationData("Excess Express Storage Car: Ragged Diary", 0x39e53b)
]

riverside: typing.List[LocationData] = [
    LocationData("Riverside Station Drawbridge: Station Key 1", 0x39e5fd),
    LocationData("Riverside Station Entrance: Close Call P", 0x39e66b),
    LocationData("Riverside Station Clockwork Room: Star Piece", 0x39e66b),
    LocationData("Riverside Station Clockwork Room: Station Key 2", 0x39e66b),
    LocationData("Riverside Station Back Exterior: HP Plus", 0x39e66b),
    LocationData("Riverside Station Back Exterior: Shine Sprite", 0x39e66b),
    LocationData("Riverside Station Back Exterior: Thunder Rage", 0x39e66b),
    LocationData("Riverside Station Tube Mode Maze: Dried Shroom", 0x39e66b),
    LocationData("Riverside Station Tube Mode Maze: P-Up D-Down", 0x39e66b),
    LocationData("Riverside Station Ultra Boots Room: Elevator Key", 0x39e66b),
    LocationData("Riverside Station Ultra Boots Room: Ultra Boots", 0x39e66b),
    LocationData("Riverside Station Goomba Room: Shine Sprite", 0x39e66b)
]

poshley_heights: typing.List[LocationData] = [
    LocationData("Poshley Heights Station: Goldbob Guide", 0x39ea1c),
    LocationData("Poshley Heights Station: HP Drain P", 0x39ea1c),
    LocationData("Poshley Heights Station: Star Piece 1", 0x39ea1c),
    LocationData("Poshley Heights Station: Star Piece 2", 0x39ea1c),
    LocationData("Poshley Heights Station: Star Piece 3", 0x39ea1c),
    LocationData("Poshley Heights Sanctum Exterior: Shine Sprite", 0x39ea1c),
    LocationData("Poshley Heights Sanctum Altar: Garnet Star", 0x39ea1c),
    LocationData("Poshley Heights Sanctum Altar: L Emblem", 0x39ea1c),
    LocationData("Poshley Heights Sanctum Altar: Shine Sprite", 0x39ea1c),
    LocationData("Poshley Heights Downtown: Fresh Pasta", 0x39ea1c),
    LocationData("Poshley Heights Downtown: Inn Coupon", 0x39ea1c),
    LocationData("Poshley Heights Downtown: Omelette Meal", 0x39ea1c),
    LocationData("Poshley Heights Downtown: Star Piece", 0x39ea1c),
]

fahr_outpost: typing.List[LocationData] = [
    LocationData("Fahr Outpost Entrance: Double Dip P", 0x39e6e5),
    LocationData("Fahr Outpost Entrance: Star Piece", 0x39e6e5),
    LocationData("Fahr Outpost Town Outskirts: Star Piece", 0x39e6e5),
    LocationData("Fahr Outpost Town: Ice Storm", 0x39e6e5),
    LocationData("Fahr Outpost Town: Inn Coupon", 0x39e6e5),
    LocationData("Fahr Outpost Town: Maple Syrup", 0x39e6e5),
    LocationData("Fahr Outpost Town: Ruin Powder", 0x39e6e5),
    LocationData("Fahr Outpost Town: Shine Sprite", 0x39e6e5),
    LocationData("Fahr Outpost Town: Shooting Star", 0x39e6e5),
    LocationData("Fahr Outpost Town: Space Food", 0x39e6e5),
    LocationData("Fahr Outpost Town: Star Piece 1", 0x39e6e5),
    LocationData("Fahr Outpost Town: Star Piece 2", 0x39e6e5),
    LocationData("Fahr Outpost Town: Stopwatch", 0x39e6e5),
    LocationData("Fahr Outpost Town: Super Shroom", 0x39e6e5),
    LocationData("Fahr Outpost West Enemy Room: Shine Sprite", 0x39e6e5),
    LocationData("Fahr Outpost West Enemy Room: Star Piece", 0x39e6e5),
    LocationData("Fahr Outpost East Enemy Room: HP Plus P", 0x39e6e5),
    LocationData("Fahr Outpost East Enemy Room: Star Piece", 0x39e6e5)
]

xnaut_fortress: typing.List[LocationData] = [
    LocationData("Moon Landing Site: Stopwatch", 0x39e70f),
    LocationData("Moon Fortress View: Power Punch", 0x39e717),
    LocationData("Moon Fortress View: Star Piece", 0x39e717),
    LocationData("Moon West Room 2: Ruin Powder", 0x39e717),
    LocationData("Moon West Room 1: Courage Shell", 0x39e717),
    LocationData("X-Naut Fortress Elevator Key Room: Elevator Key 1", 0x39e71f),
    LocationData("X-Naut Fortress Elevator Key Room: Super Shroom", 0x39e71f),
    LocationData("X-Naut Fortress Crane Room: Coin 1", 0x39e71f),
    LocationData("X-Naut Fortress Crane Room: Coin 2", 0x39e71f),
    LocationData("X-Naut Fortress Crane Room: Coin 3", 0x39e71f),
    LocationData("X-Naut Fortress Crane Room: Coin 4", 0x39e71f),
    LocationData("X-Naut Fortress Crane Room: Coin 5", 0x39e71f),
    LocationData("X-Naut Fortress Crane Room: Coin 6", 0x39e71f),
    LocationData("X-Naut Fortress Crane Room: Feeling Fine", 0x39e71f),
    LocationData("X-Naut Fortress Crane Room: Feeling Fine P", 0x39e71f),
    LocationData("X-Naut Fortress Crane Room: Star Piece", 0x39e71f),
    LocationData("X-Naut Fortress Quiz Room: Elevator Key 2", 0x39e71f),
    LocationData("X-Naut Fortress Card Key Room A: Card Key 1", 0x39e71f),
    LocationData("X-Naut Fortress Card Key Room A: Sleepy Sheep", 0x39e71f),
    LocationData("X-Naut Fortress Teleporter Room: Cog", 0x39e71f),
    LocationData("X-Naut Fortress Ceiling Grate Room: Star Piece", 0x39e71f),
    LocationData("X-Naut Fortress Office: Card Key 2", 0x39e71f),
    LocationData("X-Naut Fortress Card Key Room B: Card Key 3", 0x39e71f),
    LocationData("X-Naut Fortress Factory: Card Key 4", 0x39e71f),
    LocationData("X-Naut Fortress Factory: Ultra Shroom", 0x39e71f),
    LocationData("X-Naut Fortress Boss Room: Crystal Star", 0x39e71f),
]

palace: typing.List[LocationData] = [
    LocationData("Palace of Shadow Swoopula Staircase: Stopwatch", 0x39e5a0),
    LocationData("Palace of Shadow Bullet Bill Hallway: Shooting Star", 0x39e5a0),
    LocationData("Palace of Shadow Spike Trap Room: All or Nothing", 0x39e5a0),
    LocationData("Palace of Shadow Fire Trap Room: Boo's Sheet", 0x39e5a0),
    LocationData("Palace of Shadow Dark Bones Room: Palace Key", 0x39e55b),
    LocationData("Palace of Shadow Second Bullet Bill Hallway: Ultra Shroom", 0x39e55b),
    LocationData("Palace of Shadow Large Open Room: Coin", 0x39e55b),
    LocationData("Palace of Shadow Large Open Room: Jammin' Jelly", 0x39e55b),
    LocationData("Palace of Shadow Large Open Room: P-Up D-Down P", 0x39e55b),
    LocationData("Riddle Tower Floor 1 NW: Palace Key (Riddle Tower)", 0x39e55b),
    LocationData("Riddle Tower Floor 1 NE: Palace Key (Riddle Tower)", 0x39e55b),
    LocationData("Riddle Tower Floor 1 SW: Palace Key (Riddle Tower)", 0x39e55b),
    LocationData("Riddle Tower Floor 1 SE: Palace Key (Riddle Tower)", 0x39e55b),
    LocationData("Riddle Tower Floor 2 NW: Palace Key (Riddle Tower)", 0x39e55b),
    LocationData("Riddle Tower Floor 2 NE: Palace Key (Riddle Tower)", 0x39e55b),
    LocationData("Riddle Tower Floor 2 SW: Palace Key (Riddle Tower)", 0x39e55b),
    LocationData("Riddle Tower Floor 2 SE: Palace Key (Riddle Tower)", 0x39e55b),
    LocationData("Palace of Shadow Far Hallway 1: Thunder Rage", 0x39e563),
    LocationData("Palace of Shadow Far Backroom 1: Life Shroom", 0x39e563),
    LocationData("Palace of Shadow Far Backroom 1: Repel Cape", 0x39e563),
    LocationData("Palace of Shadow Far Backroom 2: Palace Key", 0x39e563),
    LocationData("Palace of Shadow Far Backroom 2: Point Swap", 0x39e563),
    LocationData("Palace of Shadow Far Hallway 4: Life Shroom", 0x39e563),
    LocationData("Palace of Shadow Far Hallway 4: Shooting Star", 0x39e563),
    LocationData("Palace of Shadow Gloomtail Room: Jammin' Jelly", 0x39e563),
    LocationData("Palace of Shadow Gloomtail Room: Star Key", 0x39e563),
    LocationData("Palace of Shadow Gloomtail Room: Ultra Shroom", 0x39e563),
    LocationData("Palace of Shadow Final Staircase: Jammin' Jelly", 0x39e563),
    LocationData("Palace of Shadow Final Staircase: Ultra Shroom", 0x39e563)
]

pit: typing.List[LocationData] = [
    LocationData("Pit of 100 Trials Floor 10: Sleepy Stomp", 0x39e563),
    LocationData("Pit of 100 Trials Floor 20: Fire Drive", 0x39e563),
    LocationData("Pit of 100 Trials Floor 30: Zap Tap", 0x39e563),
    LocationData("Pit of 100 Trials Floor 40: Pity Flower", 0x39e563),
    LocationData("Pit of 100 Trials Floor 50: Strange Sack", 0x39e563),
    LocationData("Pit of 100 Trials Floor 60: Double Dip", 0x39e563),
    LocationData("Pit of 100 Trials Floor 70: Double Dip P", 0x39e563),
    LocationData("Pit of 100 Trials Floor 80: Bump Attack", 0x39e563),
    LocationData("Pit of 100 Trials Floor 90: Lucky Day", 0x39e563),
    LocationData("Pit of 100 Trials Floor 100: Return Postage", 0x39e563),
    LocationData("Pit of 100 Trials Charlieton: Fire Flower", 0x39e563),
    LocationData("Pit of 100 Trials Charlieton: Honey Syrup", 0x39e563),
    LocationData("Pit of 100 Trials Charlieton: Maple Syrup", 0x39e563),
    LocationData("Pit of 100 Trials Charlieton: Mushroom", 0x39e563),
    LocationData("Pit of 100 Trials Charlieton: Super Shroom", 0x39e563),
    LocationData("Pit of 100 Trials Charlieton: Thunder Rage", 0x39e563)
]

all_locations: typing.List[LocationData] = (rogueport + sewers + petal_left + petal_right + hooktails_castle + boggly_woods +
                                            great_tree + glitzville + twilight_town + twilight_trail + creepy_steeple +
                                            pirates_grotto + keelhaul_key + excess_express + riverside + poshley_heights +
                                            fahr_outpost + xnaut_fortress + palace + pit)

location_table: typing.Dict[str, int] = {locData.name: locData.id for locData in all_locations}
