import typing

from worlds.generic.Rules import add_rule
from . import StateLogic

if typing.TYPE_CHECKING:
    from . import TTYDWorld


def set_rules(world: "TTYDWorld", excluded):
    add_rule(world.multiworld.get_location("Boggly Woods Plane Panel Room: Shine Sprite", world.player), lambda state: state.has("Koops", world.player) or state.has("Ultra Boots", world.player))
    add_rule(world.multiworld.get_location("Boggly Woods Plane Panel Room: Quake Hammer", world.player), lambda state: state.has("Plane Curse", world.player))
    add_rule(world.multiworld.get_location("Boggly Woods Outside Flurrie's House: Star Piece 1", world.player), lambda state: state.has("Plane Curse", world.player))
    add_rule(world.multiworld.get_location("Boggly Woods Outside Flurrie's House: Star Piece 2", world.player), lambda state: state.has("Plane Curse", world.player) and state.has("Paper Curse", world.player))
    add_rule(world.multiworld.get_location("Boggly Woods Outside Flurrie's House: Volt Shroom", world.player), lambda state: state.has("Plane Curse", world.player) and state.has("Paper Curse", world.player))
    add_rule(world.multiworld.get_location("Boggly Woods Flurrie's House: Flurrie", world.player), lambda state: state.has("Plane Curse", world.player) and state.has("Paper Curse", world.player) and state.has("Necklace", world.player))
    add_rule(world.multiworld.get_location("Boggly Woods Flurrie's House Backroom: Super Appeal P", world.player), lambda state: state.has("Plane Curse", world.player) and state.has("Paper Curse", world.player) and state.has("Necklace", world.player))
    add_rule(world.multiworld.get_location("Boggly Woods Flurrie's House Backroom: Star Piece", world.player), lambda state: state.has("Plane Curse", world.player) and state.has("Paper Curse", world.player) and state.has("Necklace", world.player) and state.has("Super Boots", world.player))
    add_rule(world.multiworld.get_location("Boggly Woods Outside Great Tree: FP Plus", world.player), lambda state: state.has("Super Boots", world.player))
    add_rule(world.multiworld.get_location("Great Tree Entrance: Mystic Egg", world.player), lambda state: state.has("Emerald Star", world.player))
    add_rule(world.multiworld.get_location("Great Tree Red Key Room: Mushroom", world.player), lambda state: state.has("Emerald Star", world.player))
    add_rule(world.multiworld.get_location("Keelhaul Key Jungle Entrance: Keel Mango", world.player), lambda state: state.has("Sapphire Star", world.player))
    add_rule(world.multiworld.get_location("Keelhaul Key Grotto Entrance: Wedding Ring", world.player), lambda state: state.has("Sapphire Star", world.player))
    add_rule(world.multiworld.get_location("Creepy Steeple Main Hall: Steeple Key 1", world.player), lambda state: state.has("Koops", world.player) or state.has("Yoshi", world.player))
    add_rule(world.multiworld.get_location("Creepy Steeple Upper Room: Ruby Star", world.player), lambda state: state.has("Steeple Key 1", world.player) and state.has("The Letter \"P\"", world.player))
    add_rule(world.multiworld.get_location("Creepy Steeple Underground Tube Passage: Shine Sprite", world.player), lambda state: state.has("Vivian", world.player))
    add_rule(world.multiworld.get_location("Creepy Steeple Boo Chest Room: Star Piece", world.player), lambda state: state.has("Vivian", world.player))
    add_rule(world.multiworld.get_location("Creepy Steeple Parrot Room: Mr. Softener", world.player), lambda state: state.has("Vivian", world.player))
    add_rule(world.multiworld.get_location("Creepy Steeple Parrot Room: Power Plus", world.player), lambda state: state.has("Vivian", world.player))
    add_rule(world.multiworld.get_location("Creepy Steeple Parrot Room: Star Piece", world.player), lambda state: state.has("Vivian", world.player))
    add_rule(world.multiworld.get_location("Creepy Steeple Parrot Room: Steeple Key 2", world.player), lambda state: state.has("Vivian", world.player))
    add_rule(world.multiworld.get_location("Creepy Steeple Parrot Room: The Letter \"P\"", world.player), lambda state: state.has("Vivian", world.player))
    add_rule(world.multiworld.get_location("Excess Express Middle Passenger Car: Blanket", world.player), lambda state: state.has("Autograph", world.player))
    add_rule(world.multiworld.get_location("Excess Express Back Passenger Car: Shine Sprite", world.player), lambda state: state.has("Autograph", world.player))
    add_rule(world.multiworld.get_location("Excess Express Back Passenger Car: Mushroom", world.player), lambda state: state.has("Autograph", world.player) and state.has("Blanket", world.player))
    add_rule(world.multiworld.get_location("Excess Express Storage Car: Ragged Diary", world.player), lambda state: state.has("Autograph", world.player) and state.has("Vivian", world.player) and state.has("Paper Curse", world.player))
    add_rule(world.multiworld.get_location("Excess Express Front Passenger Car: Vital Paper", world.player), lambda state: state.has("Autograph", world.player) and state.has("Vivian", world.player) and state.has("Ragged Diary", world.player) and state.has("Blanket", world.player))
    add_rule(world.multiworld.get_location("Excess Express Middle Passenger Car: Briefcase", world.player), lambda state: state.has("Autograph", world.player) and state.has("Vivian", world.player) and state.has("Ragged Diary", world.player) and state.has("Blanket", world.player) and state.has("Vital Paper", world.player))
    add_rule(world.multiworld.get_location("Excess Express Middle Passenger Car: Gold Ring", world.player), lambda state: state.has("Autograph", world.player) and state.has("Vivian", world.player) and state.has("Ragged Diary", world.player) and state.has("Blanket", world.player) and state.has("Vital Paper", world.player))
    add_rule(world.multiworld.get_location("Excess Express Middle Passenger Car: Shell Earrings", world.player), lambda state: state.has("Autograph", world.player) and state.has("Vivian", world.player) and state.has("Ragged Diary", world.player) and state.has("Blanket", world.player) and state.has("Vital Paper", world.player))
    add_rule(world.multiworld.get_location("Excess Express Dining Car: Star Piece 1", world.player), lambda state: state.has("Galley Pot", world.player))
    add_rule(world.multiworld.get_location("Excess Express Dining Car: Star Piece 2", world.player), lambda state: state.has("Shell Earrings", world.player))
    add_rule(world.multiworld.get_location("Excess Express Front Passenger Car: 30 Coins", world.player), lambda state: state.has("Gold Ring", world.player))
    add_rule(world.multiworld.get_location("Excess Express Locomotive: Star Piece", world.player), lambda state: state.has("Super Boots", world.player))
    add_rule(world.multiworld.get_location("Excess Express Middle Passenger Car: Star Piece", world.player), lambda state: state.has("Super Boots", world.player))
    add_rule(world.multiworld.get_location("Fahr Outpost Entrance: Star Piece", world.player), lambda state: state.has("Super Boots", world.player))
    add_rule(world.multiworld.get_location("Fahr Outpost Town: Star Piece 2", world.player), lambda state: state.has("Super Boots", world.player))
    add_rule(world.multiworld.get_location("Glitzville Lobby: Storage Key 2", world.player), lambda state: state.has("Flurrie", world.player))
    add_rule(world.multiworld.get_location("Glitzville Storage Back Room: Star Piece", world.player), lambda state: state.has("Flurrie", world.player) and state.has("Storage Key 1", world.player) and state.has("Storage Key 2", world.player) and state.has("Yoshi", world.player) and StateLogic.super_hammer(state, world.player))
    add_rule(world.multiworld.get_location("Glitzville Storage Room: Charge P", world.player), lambda state: state.has("Flurrie", world.player) and state.has("Storage Key 1", world.player))
    add_rule(world.multiworld.get_location("Glitzville Storage Room: Shine Sprite", world.player), lambda state: state.has("Flurrie", world.player) and state.has("Storage Key 1", world.player))
    add_rule(world.multiworld.get_location("Glitzville Storage Room: HP Plus P", world.player), lambda state: state.has("Flurrie", world.player) and state.has("Storage Key 1", world.player) and state.has("Yoshi", world.player))
    add_rule(world.multiworld.get_location("Glitzville Storage Room: Star Piece", world.player), lambda state: state.has("Super Boots", world.player) and state.has("Storage Key 1", world.player))
    add_rule(world.multiworld.get_location("Glitzville Main Square: Power Plus P", world.player), lambda state: state.has("Super Boots", world.player))
    add_rule(world.multiworld.get_location("Glitzville Main Square: Star Piece 4", world.player), lambda state: state.has("Super Boots", world.player))
    add_rule(world.multiworld.get_location("Glitzville Main Square: Star Piece 5", world.player), lambda state: state.has("Super Boots", world.player) and (state.has("Koops", world.player) or state.has("Tube Curse", world.player)))
    add_rule(world.multiworld.get_location("Glitzville Minor-League Room: Yoshi", world.player), lambda state: state.has("Super Boots", world.player) and state.has("Plane Curse", world.player))
    add_rule(world.multiworld.get_location("Glitzville Minor-League Room: Dubious Paper", world.player), lambda state: StateLogic.super_hammer(state, world.player) and state.has("Yoshi", world.player))
    add_rule(world.multiworld.get_location("Glitzville Major-League Room: Champ's Belt", world.player), lambda state: state.has("Flurrie", world.player) and state.has("Yoshi", world.player))
    add_rule(world.multiworld.get_location("Glitzville Major-League Room: Ice Storm", world.player), lambda state: state.has("Yoshi", world.player))
    add_rule(world.multiworld.get_location("Glitzville Arena: Gold Star", world.player), lambda state: state.has("Yoshi", world.player) and state.has("Flurrie", world.player) and StateLogic.super_hammer(state, world.player))
    add_rule(world.multiworld.get_location("Glitzville Promoter's Office: Star Piece 2", world.player), lambda state: state.has("Yoshi", world.player) and state.has("Flurrie", world.player) and StateLogic.super_hammer(state, world.player))
    add_rule(world.multiworld.get_location("Great Tree Red/Blue Cages: Star Piece", world.player), lambda state: state.has("Blue Key", world.player) and state.has("Super Boots", world.player))
    add_rule(world.multiworld.get_location("Great Tree Entrance: Puni Orb", world.player), lambda state: state.has("Red Key", world.player))
    add_rule(world.multiworld.get_location("Great Tree Bubble Room: Shine Sprite", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player))
    add_rule(world.multiworld.get_location("Great Tree Bubble Room: Thunder Rage", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player))
    add_rule(world.multiworld.get_location("Great Tree Zigzag Room: Coin", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player))
    add_rule(world.multiworld.get_location("Great Tree Zigzag Room: Damage Dodge P", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player))
    add_rule(world.multiworld.get_location("Great Tree Zigzag Room: Star Piece", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player))
    add_rule(world.multiworld.get_location("Great Tree Shop: Honey Syrup", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player))
    add_rule(world.multiworld.get_location("Great Tree Shop: HP Drain", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player))
    add_rule(world.multiworld.get_location("Great Tree Shop: Ice Storm", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player))
    add_rule(world.multiworld.get_location("Great Tree Shop: Mini Mr.Mini", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player))
    add_rule(world.multiworld.get_location("Great Tree Shop: Mushroom", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player))
    add_rule(world.multiworld.get_location("Great Tree Shop: Mystery", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player))
    add_rule(world.multiworld.get_location("Great Tree Red Key Room: Blue Key", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player))
    add_rule(world.multiworld.get_location("Great Tree Super Boots Room: Super Boots", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Blue Key", world.player))
    add_rule(world.multiworld.get_location("Great Tree 100-Puni Pedestal: Coin", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Blue Key", world.player))
    add_rule(world.multiworld.get_location("Great Tree 100-Puni Pedestal: Star Piece", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Blue Key", world.player))
    add_rule(world.multiworld.get_location("Great Tree Fake Pedestal: Star Piece", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Blue Key", world.player))
    add_rule(world.multiworld.get_location("Great Tree Entrance: Emerald Star", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Blue Key", world.player) and state.has("Koops", world.player))
    add_rule(world.multiworld.get_location("Great Tree Elevator Pedestal: Mushroom", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Blue Key", world.player) and state.has("Koops", world.player))
    add_rule(world.multiworld.get_location("Great Tree Escape Ambush Room: Star Piece", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Blue Key", world.player) and state.has("Koops", world.player))
    add_rule(world.multiworld.get_location("Great Tree Pool Room: Dizzy Dial", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Blue Key", world.player) and state.has("Koops", world.player))
    add_rule(world.multiworld.get_location("Great Tree Pool Room: Shine Sprite", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Blue Key", world.player) and state.has("Koops", world.player))
    add_rule(world.multiworld.get_location("Great Tree Pool Room: Shrink Stomp", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Blue Key", world.player) and state.has("Koops", world.player))
    add_rule(world.multiworld.get_location("Great Tree Lower Duplex: Coin", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Blue Key", world.player) and state.has("Super Boots", world.player))
    add_rule(world.multiworld.get_location("Great Tree Middel Duplex: Shine Sprite", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Plane Curse", world.player))
    add_rule(world.multiworld.get_location("Great Tree Red Key Room: Charge", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Super Boots", world.player))
    add_rule(world.multiworld.get_location("Great Tree Red Key Room: Shine Sprite", world.player), lambda state: state.has("Red Key", world.player) and state.has("Puni Orb", world.player) and state.has("Flurrie", world.player) and state.has("Super Boots", world.player))
    add_rule(world.multiworld.get_location("Great Tree 10-Puni Pedestal: Star Piece", world.player), lambda state: state.has("Super Boots", world.player))

