from BaseClasses import Location

class LocationData():
    def __init__(self, name: str, id: int, tags: list[str]):
        self.name = name
        self.id = id
        self.tags = tags

all_locations: list[LocationData] = []
index = 0

# Mission rank locations
for level in ["Sawmill", "Cul-De-Sac", "Construction", "Downtown"]:
    for rank in ["C", "B", "A"]:
        all_locations += [LocationData(f"{level}: Mission {i} Rank {rank}", index + i, [level, rank, "mission"]) for i in range(1, 21)]
        index += 20

# Interactable object locations
interactable_objects: dict[str, list[tuple[str, str]]] = {
    "Sawmill": [
        ("1A_Int_Door01", "Door 1"),
        ("1A_Int_Door02", "Door 2"),
        ("1A_Int_Door03", "Door 3"),
        ("1A_Int_Door04", "Door 4"),
        ("1A_Int_Door05", "Door 5"),
        ("1A_Int_Door06", "Door 6"),
        ("1A_Int_HP001", "Hiding Spot 1"),
        ("1A_Int_HP002", "Hiding Spot 2"),
        ("1A_Int_HP003", "Hiding Spot 3"),
        ("1A_Int_HP004", "Hiding Spot 4"),
        ("1A_Int_HP005", "Hiding Spot 5"),
        ("1A_Int_HP006", "Hiding Spot 6"),
        ("1A_Int_HP007", "Hiding Spot 7"),
        ("1A_Int_HP008", "Hiding Spot 8"),
        ("1A_Int_HP009", "Hiding Spot 9"),
        ("1A_Int_HP010", "Hiding Spot 10"),
        ("1A_Int_HP011", "Hiding Spot 11"),
        ("1A_Int_HP012", "Hiding Spot 12"),
        ("1A_Int_HP013", "Hiding Spot 13"),
        ("1A_Int_HP014", "Hiding Spot 14"),
        ("1A_Int_HP015", "Hiding Spot 15"),
        ("1A_Int_HP016", "Hiding Spot 16"),
        ("1A_Int_HP017", "Hiding Spot 17"),
        ("1A_Int_HP018", "Hiding Spot 18"),
        ("1A_Int_HP019", "Hiding Spot 19"),
        ("1A_Int_HP020", "Hiding Spot 20"),
        ("1A_Int_HP021", "Hiding Spot 21"),
        ("1A_Int_HP022", "Hiding Spot 22"),
        ("1A_Int_HP023", "Hiding Spot 23"),
        ("1A_Int_HP024", "Hiding Spot 24"),
        ("1A_Int_HP025", "Hiding Spot 25"),
        ("1A_Int_HP026", "Hiding Spot 26"),
        ("1A_Int_HP027", "Hiding Spot 27"),
        ("1A_Int_HP028", "Hiding Spot 28"),
        ("1A_Int_HP030", "Hiding Spot 29"),
        ("1A_Int_HP031", "Hiding Spot 30"),
        ("1A_Int_HP032", "Hiding Spot 31"),
        ("1A_Int_HP033", "Hiding Spot 32"),
        ("1A_Int_HP034", "Hiding Spot 33"),
        ("1A_Int_HP035", "Hiding Spot 34"),
        ("1A_Int_HP036", "Hiding Spot 35"),
        ("1A_Int_HP037", "Hiding Spot 36"),
        ("1A_Int_HP038", "Hiding Spot 37"),
        ("1A_Int_HP039", "Hiding Spot 38"),
        ("1A_Int_HP040", "Hiding Spot 39"),
        ("1A_Int_HP041", "Hiding Spot 40"),
        ("1A_Int_Ladder01", "Ladder"),
        ("1A_Int_Portaloo01", "Porta-Potty"),
        ("1A_Int_Shortcut01", "Shortcut 1"),
        ("1A_Int_Shortcut02", "Shortcut 2"),
        ("1A_Int_Tree01", "Tree 1"),
        ("1A_Int_Tree02", "Tree 2"),
        ("1PA_Int_BridgePanel01", "Bridge Panel"),
    ],
    "Cul-De-Sac": [
        ("2A_Bin 001", "Trash Can 1"),
        ("2A_Bin 002", "Trash Can 2"),
        ("2A_Bin 003", "Trash Can 3"),
        ("2A_Bin 004", "Trash Can 4"),
        ("2A_Bin 005", "Trash Can 5"),
        ("2A_Bin 006", "Trash Can 6"),
        ("2A_Bin 008", "Trash Can 7"),
        ("2A_Bin 009", "Trash Can 8"),
        ("2A_Bin 010", "Trash Can 9"),
        ("2A_Bin 011", "Trash Can 10"),
        ("2A_Bin 013", "Trash Can 11"),
        ("2A_Bin 015", "Trash Can 12"),
        ("2A_Bin1", "Trash Can 13"),
        ("2A_Int_Door 001", "Door 1"),
        ("2A_Int_Door 002", "Door 2"),
        ("2A_Int_Door 003", "Door 3"),
        ("2A_Int_Door 004", "Door 4"),
        ("2A_Int_Door 005", "Door 5"),
        ("2A_Int_Door 006", "Door 6"),
        ("2A_Int_Door 007", "Door 7"),
        ("2A_Int_Door 008", "Door 8"),
        ("2A_Int_Door 009", "Door 9"),
        ("2A_Int_Door 010", "Door 10"),
        ("2A_Int_Door 011", "Door 11"),
        ("2A_Int_Door 012", "Door 12"),
        ("2A_Int_Door 013", "Door 13"),
        ("2A_Int_Door 014", "Door 14"),
        ("2A_Int_Door 015", "Door 15"),
        ("2A_Mailbox 001", "Mailbox 1"),
        ("2A_Mailbox 002", "Mailbox 2"),
        ("2A_Mailbox1", "Mailbox 3"),
        ("2A_Mailbox2", "Mailbox 4"),
        ("2A_Mailbox3", "Mailbox 5"),
        ("2A_Mailbox4", "Mailbox 6"),
        ("2A_Mailbox5", "Mailbox 7"),
        ("2A_Mailbox6", "Mailbox 8"),
        ("2A_Mailbox7", "Mailbox 9"),
        ("2A_conserv_glass 008", "Greenhouse Window"),
        ("2A_conservatory 001", "Greenhouse"),
        ("2A_crate 001", "Crate 1"),
        ("2A_crate 002", "Crate 2"),
        ("2A_treehouse 001", "Treehouse"),
        ("Prop Tree 001", "Tree 1"),
        ("Prop Tree 002", "Tree 2"),
        ("Prop Tree 003", "Tree 3"),
        ("Prop Tree 004", "Tree 4"),
        ("Prop Tree 005", "Tree 5"),
        ("Prop Tree 006", "Tree 6"),
        ("Prop Tree 007", "Tree 7"),
        ("Prop Tree 008", "Tree 8"),
        ("Prop Tree 009", "Tree 9"),
        ("Prop Tree 010", "Tree 10"),
        ("Prop Tree 011", "Tree 11"),
        ("Prop Tree 012", "Tree 12"),
        ("Prop Tree 013", "Tree 13"),
        ("Prop Tree 014", "Tree 14"),
        ("Prop Tree 015", "Tree 15"),
        ("Prop Tree 016", "Tree 16"),
        ("Prop Tree 017", "Tree 17"),
        ("Prop Tree 018", "Tree 18"),
        ("Prop Tree 019", "Tree 19"),
        ("Prop Tree 020", "Tree 20"),
        ("Prop Tree 021", "Tree 21"),
        ("Prop Tree 022", "Tree 22"),
        ("Prop Tree 023", "Tree 23"),
        ("Prop Tree001", "Tree 24"),
    ],
    "Construction": [
        ("3A_Barrel01", "Barrel 1"),
        ("3A_Barrel02", "Barrel 2"),
        ("3A_Barrel03", "Barrel 3"),
        ("3A_Barrel04", "Barrel 4"),
        ("3A_Barrel05", "Barrel 5"),
        ("3A_Barrel06", "Barrel 6"),
        ("3A_Barrel07", "Barrel 7"),
        ("3A_Crate01", "Crate 1"),
        ("3A_Crate02", "Crate 2"),
        ("3A_Crate03", "Crate 3"),
        ("3A_Crate04", "Crate 4"),
        ("3A_Crate05", "Crate 5"),
        ("3A_Crate06", "Crate 6"),
        ("3A_Crate07", "Crate 7"),
        ("3A_DiggerScoop", "Digger Scoop"),
        ("3A_Door01", "Door 1"),
        ("3A_Door02", "Door 2"),
        ("3A_Door02_knocker", "Door 2 Knocker"),
        ("3A_Door03", "Door 3"),
        ("3A_Door03_knocker", "Door 3 Knocker"),
        ("3A_Door_Portaloo", "Porta-Potty"),
        ("3A_LadderBase", "Ladder"),
        ("3A_Manhole1", "Manhole 1"),
        ("3A_Manhole2", "Manhole 2"),
        ("3A_PipeEnd02", "Pipe End 1"),
        ("3A_PipeEnd04", "Pipe End 2"),
        ("3A_PipeEndRaised1", "Raised Pipe End"),
        ("3A_PipeFlat", "Flat Pipe"),
        ("3A_PipeRamp", "Pipe Ramp"),
        ("3A_PipeV", "V Pipe"),
        ("3A_Sandpile", "Sand Pile"),
        ("3A_Skip1", "Dumpster 1"),
        ("3A_Skip2", "Dumpster 2"),
    ],
    "Downtown": [
        ("4A_HP 001", "Hiding Spot 1"),
        ("4A_HP 003", "Hiding Spot 2"),
        ("4A_HP 004", "Hiding Spot 3"),
        ("4A_HP 006", "Hiding Spot 4"),
        ("4A_HP 007", "Hiding Spot 5"),
        ("4A_HP 008", "Hiding Spot 6"),
        ("4A_HP 009", "Hiding Spot 7"),
        ("4A_HP 010", "Hiding Spot 8"),
        ("4A_HP 014", "Hiding Spot 9"),
        ("4A_HP 015", "Hiding Spot 10"),
        ("4A_HP 017", "Hiding Spot 11"),
        ("4A_HP 019", "Hiding Spot 12"),
        ("4A_HP 022", "Hiding Spot 13"),
        ("4A_HP 023", "Hiding Spot 14"),
        ("4A_HP 025", "Hiding Spot 15"),
        ("4A_HP 027", "Hiding Spot 16"),
        ("4A_HPskip 001", "Dumpster"),
        ("4A_Int_AptDoor_ 001", "Apartment Door 1"),
        ("4A_Int_AptDoor_ 03", "Apartment Door 2"),
        ("4A_Int_AptDoor_ 04", "Apartment Door 3"),
        ("4A_Int_AptDoor_01", "Apartment Door 4"),
        ("4A_Int_AptDoor_02", "Apartment Door 5"),
        ("4A_Int_NewspaperMachine01", "Newspaper Machine"),
        ("4A_Int_SC03", "Shopping Cart 1"),
        ("4A_Int_SC04", "Shopping Cart 2"),
        ("4A_Int_StoreDoor02", "Store Door"),
        ("4A_SceneryProp_Car 006", "Car"),
        ("4A_Subway1_entrance", "Subway 1 Entrance"),
        ("4A_Subway1_exit", "Subway 1 Exit"),
        ("4A_Subway2_entrance", "Subway 2 Entrance"),
        ("4A_Subway2_exit", "Subway 2 Exit"),
        ("4A_Telemaphone_door", "Phone Booth 1"),
        ("4A_Telemaphone_door2", "Phone Booth 2"),
    ],
}

# Mission IDs used: index+1 through index+20 per batch, so max mission ID = index
# Interactable IDs start after
index += 1

for level, objects in interactable_objects.items():
    for entity_name, display_name in objects:
        all_locations.append(LocationData(
            f"{level}: {display_name}",
            index,
            [level, "interactable"]
        ))
        index += 1


def get_locations_by_tag(tag: str):
    return [location for location in all_locations if tag in location.tags]

class SneakKingLocation(Location):
    game = "Sneak King"
